### ISSUE TITLE
修改问题

### ISSUE THREAD

**Issue by remember17** [fi3ework/hexo-theme-archer#1]
你好，
1. 进入发布好了的文章之后下拉上拉，会有一个半透明的遮罩在最顶部，显示标题。我感觉整个页面的阅读空间被压缩了，怎么才能去掉这个功能呢？
2. 可以自己改变首页或文章里面的字体么？
3. 文章里面banner上的标题字体在哪里能调小么？因为如果标题太长久会显示不全了
4. 页面最右侧感觉有一条缝

**Comment by fi3ework** [comment]
您好

- [x] 遮罩确实有些碍事，已经修改了，在下滑时会自动隐藏，上滑时才会显示。
- [x] 可以，不过目前暂不支持通过配置文件直接更改。需要你进行二次开发，参照[二次开发文档](https://github.com/fi3ework/hexo-theme-archer/blob/master/docs/develop-guide.md)。如果你只想更改字体的话，可以不需要参照二次开发文档，直接在`layout\base-head.ejs`中修改`src: url('<%- url_for('/font/Oswald-Regular.ttf') %>');`，改为你在对应路径添加的字体（不要修改`font-family`的名称），再重新生成即可。
- [x] 现在字体变小了，能够容纳更长的标题了。
- [x] 最右侧的其实不是缝，是导航条。我把导航条的背景色设为白色了，所以造成了“缝“的错觉，现在背景色改深了一点。

感谢使用:)
