### ISSUE TITLE
如何启用分享以及QR Code

### ISSUE THREAD

**Issue by fchypzero** [fi3ework/hexo-theme-archer#10]
我看到在 /layout/_partial/ 下是有 bae-share 和 base-qr-box 的，但是实际上我的 DEMO 上没有发现有启用到这两个，而且也没在文档说明怎么启用，请问一下相应的启用方法。

**Comment by fi3ework** [comment]
这个暂时没有，后来改界面我一懒就把分享给删了-_-，后续也许会加进来。

**Comment by Jiiiiiin** [comment]
期待哦 @fchypzero

**Comment by fi3ework** [comment]
现在已经可以用分享和二维码了，使用的是百度分享 @Jiiiiiin
