### ISSUE TITLE
About sidebar not visible in mobile devices

### ISSUE THREAD

**Issue by pfrankw** [fi3ework/hexo-theme-archer#100]
Hi!

First of all thank you for this amazing theme :)

I noticed a little problem within it: The about sidebar is not visible when visited from mobile devices, and so it is not possible to reach the about page for them.

Thanks.

**Comment by fi3ework** [comment]
Hi!
I know it could not reach the about page from mobile devices. It's a feature not a bug cause I didn't think it's important to reach about page from mobile devices. But several issues has proved I was wrong. I will 'fix' the feature asap.

Thanks for your issue 😀

**Comment by pfrankw** [comment]
Thank you very much :)

You have an email!
