### ISSUE TITLE
建议：文章内容的英文字体默认换成 Titillium Web 这个字体

### ISSUE THREAD

**Issue by PopeyeZhong** [fi3ework/hexo-theme-archer#102]
Titillium Web 字体用来做文章内容的英文字体很漂亮，我是在下面这个网址看到的：
https://walterlv.github.io/post/case-of-dotnet-writing.html

不知楼主是否喜欢。

**Comment by fi3ework** [comment]
字体挺好看的，但是需要通过 font-face 下载字体，在这个自定义字体下载完之前，只能空白显示 或者 等字体下载完毕之后问题“闪一下”刷新，感觉受益并没有代价来的大。
主题只引用了一种叫 Oswald 的第三方字体做标题，其他都是尽量使用系统自带的字体。
所以目前字体还是决定维持现状啦。
