### ISSUE TITLE
代码高亮粉红色背景太别扭了,...求教怎样调暗色背景

### ISSUE THREAD

**Issue by YinWC** [fi3ework/hexo-theme-archer#105]

**Comment by fi3ework** [comment]
修改 `scss/_post/_code.scss` 文件中 light color 下面的配色方案即可，配色的颜色去 [highlightjs](https://github.com/isagalaev/highlight.js/tree/master/src/styles hightlight) 这个库里选一个喜欢的颜色对应着替换即可，我就是选的其中的一个，换完之后参照一下文档里提供的 二次开发文档 重新生成一次即可。
暂时还没有更简单的替换代码配色的方案。

**Comment by YinWC** [comment]
OKOK,thanks.

**Comment by XinAnzzZ** [comment]
@YinWC 可以给个配色的步骤吗？不懂前端，十分感谢。

**Comment by YinWC** [comment]
改一下json文件就行了




------------------ 原始邮件 ------------------
发件人: "心安"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 下午5:01
收件人: "fi3ework/hexo-theme-archer"<hexo-theme-archer@noreply.github.com>;
抄送: "2506079477"<2506079477@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [fi3ework/hexo-theme-archer] 代码高亮粉红色背景太别扭了,...求教怎样调暗色背景 (#105)




@YinWC 可以给个配色的步骤吗？不懂前端，十分感谢。
