### ISSUE TITLE
目录部分，当目录比较长的时候，后面就截断了。

### ISSUE THREAD

**Issue by hulichao** [fi3ework/hexo-theme-archer#107]
能做成，目录读取当前光标位置，上下固定范围的目录这样或者滚动条？？？

**Comment by fi3ework** [comment]
可以提供一个链接吗

**Comment by hulichao** [comment]
这一款next主题的就有http://chenfengkg.cn/optimize-blog/
1.目录有下拉框，
2.下拉框会随着文章，形成滑动窗口的效果。

**Comment by hulichao** [comment]
对了还有就是目录截断，太长的目录自动省略后面的部分。。类似上面这个博客的样子。

**Comment by fi3ework** [comment]
其实现在的默认是有折叠的，默认折叠到第一级标题，只有在你浏览比如 2.3.4 时才会展开 2.3.4 对应的父层级。我看了下你的博客，是因为你的第一级标题太多了... 这个只能考虑给目录栏加个滚动了。
至于目录截断这个问题，我倾向于不截断（因为如果目录就是需要很长，截断了就无法正确知道是哪个目录了），换一行显示就可以了，只要加上滚动就不怕目录有多长了。

**Comment by fi3ework** [comment]
这个 bug 会修复的。

**Comment by hulichao** [comment]
嗯嗯，主要的是滚动，一级目录太多了。
支持！！！

**Comment by hulichao** [comment]
还有那个滚动是滑动窗口的滚动，不是普通的滚动，随着文章的下翻，只显示目前正在读到的标题内容的附件的标题。

**Comment by hulichao** [comment]
附近。。。

**Comment by fi3ework** [comment]
archer 现在也是啊，比如 [这个](http://firework.studio/archer-demo/2013-12-24/elements/) 滚动的显示只显示父标题。
ps：issue 下的回复是支持修改的 :smile:

**Comment by hulichao** [comment]
我再表述一下，我表达的可能不太清楚。
1.增加滚动条
2.滚动条内的父级目录随着下翻子目录自动打开（已有）
3.父级目录随着下翻也自动滚动（这个是我提到的）
效果呢就是，http://chenfengkg.cn/optimize-blog/类似这个博客里的效果（**重点** 用鼠标往下滑动文章，目录部分也跟着滑动）
ps:最后发现2和3其实早已实现了，只是没注意到，因为没有1的存在，所以3可能不明显。
不知道表达清楚没。。。。哈哈！！！

**Comment by fi3ework** [comment]
清楚! got it!

**Comment by gjgjh** [comment]
请问这个问题解决了吗？同样遇到这个问题了

**Comment by LolipopJ** [comment]
@hulichao @gjgjh 最近我们修复了这个问题！😄
