### ISSUE TITLE
点击文章标签后侧边栏弹出时未自动切换至Tag显示

### ISSUE THREAD

**Issue by nahumerous** [fi3ework/hexo-theme-archer#11]
侧边栏默认Archive没做切换

**Comment by fi3ework** [comment]
感谢使用。
你的意思是点击tag时会有一个小的从archive切换到tag的滑动动画是吧，这个目前是简单的加了一个触发所以会有这么一个小的动画露出来，不是什么大问题，在下个版本会改掉。

**Comment by fi3ework** [comment]
请问是什么浏览器下，Firefox吗

**Comment by nahumerous** [comment]
Safari也会有这个问题，虽然弹出了sidebar却没有触发tag的点击事件。

**Comment by fi3ework** [comment]
亲测最新版本在macOS和iOS下都已没有问题了，可以pull一下再试试哈
