### ISSUE TITLE
文章对应的Index为0kb???

### ISSUE THREAD

**Issue by DeveloperHu** [fi3ework/hexo-theme-archer#114]
![image](https://user-images.githubusercontent.com/21489973/41458406-144a863e-70b9-11e8-8489-ac1fc480b5ae.png)

**Comment by DeveloperHu** [comment]
能发一个文章的Index.html给我吗？

**Comment by fi3ework** [comment]
好像已经解决了哈

**Comment by DeveloperHu** [comment]
@fi3ework 大佬还是不行啊？？
https://segmentfault.com/q/1010000015318014
能看看是哪里的问题吗？第一次用这个搭博客

**Comment by fi3ework** [comment]
建议你重新找个文件夹开一个 Hexo 的仓库，按照 Hexo官方官网提供的步骤生成，并且检查是否 node 的版本过低，这个并不是主题的问题哦。

**Comment by DeveloperHu** [comment]
@fi3ework 好的 谢谢大佬！！！
