### ISSUE TITLE
我该如何添加一些字体在archer？

### ISSUE THREAD

**Issue by helGayhub233** [fi3ework/hexo-theme-archer#117]
嘿，你的主题很棒，并且正在使用。主题自带的字体有些单调，我想让它支持更多的字体，在哪导入呢？

**Comment by fi3ework** [comment]
你好，不知道你想修改的是哪个字体，整个主题只应用了两个字体，一个是头图的标题上的字体，一个是正文的字体，都定义在[这里](https://github.com/fi3ework/hexo-theme-archer/blob/98aa14a342481fcea9d26b653dfa5b9113176ab1/src/scss/_variables.scss#L4-L22)，如果想要修改的话，可以参照文档中的二次开发文档。
