### ISSUE TITLE
hexo+algolia按照说明配置后没有出现搜索框

### ISSUE THREAD

**Issue by ifishzz** [fi3ework/hexo-theme-archer#118]
algolia后台能收到数据
但是我的https://ifishzz.github.io/ 页面没有搜索框
还需要加什么代码吗

**Comment by fi3ework** [comment]
因为你的主题版本太低了，请更新到最新的主题。

**Comment by ifishzz** [comment]
请问，需要怎么更新。更新了是不是需要重新配置

**Comment by fi3ework** [comment]
简单粗暴的方法就是把你 archer 主题的 config.yml 复制出来，然后删掉，重新 clone，再复制回去

**Comment by fi3ework** [comment]
按理说不会的啊，是直接复制文档中的命令安装的吗

**Comment by fi3ework** [comment]
```bash
npm i hexo-generator-json-content --save && npm i --save hexo-wordcount && git clone https://github.com/fi3ework/hexo-theme-archer.git themes/archer --depth=1
```

**Comment by hulichao** [comment]
hahh, 我想说的是，你的demo博客的搜索点了没反应。哈哈哈哈

**Comment by fi3ework** [comment]
@hulichao 我用的模板的 config.yml deploy 的...，Algolia 的配置被冲掉了，晚上把 appKey填上再 deploy 一次 :joy: ...

**Comment by ifishzz** [comment]
@fi3ework 全部卸载掉终于重新安装好了
![image](https://user-images.githubusercontent.com/37442408/41976060-a04c9afc-7a4e-11e8-9824-59007f1f1d9e.png)
