### ISSUE TITLE
有个问题是hexo博客据说不能被百度收录

### ISSUE THREAD

**Issue by hulichao** [fi3ework/hexo-theme-archer#119]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
我的博客hulichao.top 博客不能被百度收录，这个问题想请教群主一下，我也是双仓库，网上该弄的都弄了。
**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)
嗯
**如何复现（To Reproduce）**
百度收不到怎办
**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
www.hulichao.top
**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**
求教
**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by fi3ework** [comment]
看下 [这个文章](https://www.jianshu.com/p/25145964abf3)，是需要自己给百度提交的。
而且，百度的收录我记得是比较慢的，可能要有以月为单位的延迟。
再而且，好像 github 是不允许百度的爬虫爬的，对百度，只能自己去提交。

**Comment by hulichao** [comment]
是滴

**Comment by hulichao** [comment]
http://hulichao.top/baidusitemap.xml 不信你看

**Comment by fi3ework** [comment]
感觉这个东西不关主题的事啊，整个过程一点都没牵扯到主题，感觉是百度的锅...

**Comment by MOREFOX** [comment]
github代码托管的，百度爬虫返回信息是：DNS拒绝访问。我换到coding代码托管就可以被抓取了，收录也很快。但coding托管是收费的，也有免费的但会在点开时出现个前置广告页（不交钱就是坑

**Comment by fi3ework** [comment]
@MOREFOX MOR 你在 codings 托管的页面的首页加上 “托管 by codings” 的图标和链接，在 codings 审核过后就可以没有前置广告业了

**Comment by hulichao** [comment]
是的，我已经按这个做法做过了，现在在百度站长那里能看到提交记录，sitemap和主动提交的，这个提交链接与域名收录是一样嘛？ 域名一直没被收录是怎么回事呢？

**Comment by fi3ework** [comment]
看下[这个](https://www.zhihu.com/question/30898326)

**Comment by hulichao** [comment]
coding这种方式不能了么？

**Comment by hulichao** [comment]
coding的logo我都放上去好久了，好像还是不行。

**Comment by fi3ework** [comment]
@hulichao 
https://coding.net/help/doc/pages/guide-page.html

**Comment by hulichao** [comment]
这个弄过了呀。。。。

**Comment by fi3ework** [comment]
那就不知道了呀。。。。这是 coding 的锅

**Comment by hulichao** [comment]
coding那边的ip好像一直在变，，，，，

**Comment by hulichao** [comment]
哎。。。。。不知道怎么弄了。楼主是用什么方式，的

**Comment by fi3ework** [comment]
我没用 coding 啊，我现在写博客都不用 hexo 了，直接写 issue。。

**Comment by fi3ework** [comment]
我看下你的 coding 的主页

**Comment by hulichao** [comment]
hulichao.coding.me/myblog

**Comment by hulichao** [comment]
不写博客了么，只写issue？？

**Comment by fi3ework** [comment]
https://github.com/fi3ework/blog/issues

**Comment by hulichao** [comment]
可以呀，这个感觉挺方便把，应该。哈哈哈😄
