### ISSUE TITLE
請教 RSS 的標題問題

### ISSUE THREAD

**Issue by iverwei** [fi3ework/hexo-theme-archer#120]
你好，不好意思想請教大大您一個問題，
我目前已經有成功的啟用了 RSS 的訂閱功能，
但是當我要訂閱我自己的時候，
發現我並沒有頭像的圖片，
且我的標題名稱是 Hexo，而非我的部落格名稱，
不知道這部分要去哪邊更改呢？

因為網路找不太到相關的問題，
所以不知道怎麼修改，
希望您可以提點一下，
真的很不好意思，在麻煩你了，謝謝你。
這是我的部落格連結：https://iverwei.github.io

**Comment by fi3ework** [comment]
你好，我个人没怎么使用过 rss，请告知下使用的 rss 客户端及操作系统方便我测试验证一下。

**Comment by iverwei** [comment]
感謝大大好快的回覆，
我使用的系統是 macOS 和 iOS，
App 名稱皆為 Feedly

真的很謝謝你，這樣子的麻煩妳，感謝。

**Comment by fi3ework** [comment]
你好，我试了下 macOS 下的 feedly，确实是如你所说。
![image](https://user-images.githubusercontent.com/12322740/42019487-dadbbf9c-7ae7-11e8-8033-62b0fd2274d6.png)
顺便看了下，这个 app 的上次更新是 2014 年了... 似乎已经没有在维护了。
我用 Reeder 这个 rss 订阅器试了下
![image](https://user-images.githubusercontent.com/12322740/42019532-f8b77fe2-7ae7-11e8-8691-ca42636e5c14.png)
是可以正常订阅的。
所以有两种解决方法：
1. 换一个更好的 rss 阅读器。
2. xml 是通过 [这个](https://github.com/hexojs/hexo-generator-feed) 插件生成的，生成的 xml 有两种格式
> Generate Atom 1.0 or RSS 2.0 feed.
默认的是第一种，你可以按照文档中的说明修改为 RSS 2.0，并将 archer 中 config 改为 `rss: /rss2.xml`，也许 feedly 并不支持 atom1.0 的格式，如果还不行的话，可能就只能换个阅读器了，毕竟已经四年更新了 :joy:

**Comment by iverwei** [comment]
好的，太感謝大大的解答了，
剛剛按照個大大的提示改了 RSS 2.0，
發現在 feedly 上還是一樣的結果，
看來可以安心的換個閱讀器了 😅

但至少我的疑問解決了，
真的很謝謝你大大您，萬分感激！

**Comment by fi3ework** [comment]
不客气~
