### ISSUE TITLE
markdown 代码样式设置

### ISSUE THREAD

**Issue by LeeHao92** [fi3ework/hexo-theme-archer#123]
之前用过您的博客风格，代码样式是黑色主题。

![image](https://user-images.githubusercontent.com/22903176/42133512-4a604b3a-7d5e-11e8-9c98-b2d64d22bb6c.png)

现在却是黄色的

![image](https://user-images.githubusercontent.com/22903176/42133522-5c693d5a-7d5e-11e8-8aac-356a3f1d13b4.png)

如何修改为黑色背景？

**Comment by fi3ework** [comment]
怎么大家都这么喜欢原来的代码样式 :joy: 看来真的要添加一个样式选择的配置项了
