### ISSUE TITLE
请求帮助OvO,关于文章分享。

### ISSUE THREAD

**Issue by dempsterleung** [fi3ework/hexo-theme-archer#125]
文章用twitter分享出现问题，别的分享方式都没有毛病，不知道问题出在哪里。想请大神帮忙看看问题在哪里，谢谢。https://liangzhicheng.cc/2018/06/29/Welcome-to-My-Pages/

**Comment by fi3ework** [comment]
这个似乎是 twitter 的分享外链挂了，不知道是暂时的还是永久的，我先 reopen 了，找到解决方法再 close 掉。

**Comment by fi3ework** [comment]
确实没问题了，pc 和 移动端都没问题了，但昨天点不开，可能是 twitter 的问题...
