### ISSUE TITLE
推荐一个背景图随机生成api

### ISSUE THREAD

**Issue by hulichao** [fi3ework/hexo-theme-archer#127]
**提出你对主题的建议（Suggest your idea）**
直接上api:https://source.unsplash.com/random/1600x500
**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**
后面有好多参数可以调，其中就包括图片大小和范围等等，也可以是自己收藏的图片，等等。。很方便
**提出其他的你考虑到的点（Describe alternatives you've considered）**
哈哈哈哈，感觉不错。推荐给大家使用。
**其他**

**Comment by hulichao** [comment]
还有一点，完全免费，商业也oj8k

**Comment by fi3ework** [comment]
这个很好啊，感谢分享。
暂时不将这个链接作为默认的头图，因为 1. 虽然 unsplash 的图单纯论质量来说都很高，但考虑到作为背景和方便阅读并是所有图片都适合做头图，如果是选择自己收藏的图就需要一个事先收集的过程 2. unsplash 是国外的网站，好像被墙搞的很慢。
但是这个 API 确实不错，适合喜欢自己折腾的用户使用，我会将它加入文档中。
感谢~

**Comment by hulichao** [comment]
嗯嗯
