### ISSUE TITLE
Tags功能不显示文章，而Categories功能正常

### ISSUE THREAD

**Issue by lirenchong** [fi3ework/hexo-theme-archer#129]
## Tags功能不显示文章，而Categories功能正常

第一眼在所有主题中就看中了Archive的赏心悦目，决定深度使用，挖掘各种潜能。感谢作者。

### 问题描述

![mark](http://pb2l0ws93.bkt.clouddn.com/lirenchong/180705/llaK03fFdG.png?imageslim)

作为0基础，花了两天时间鼓捣Hexo的新手，在搜寻过网上各种方法后，对Tag功能点击后无法显示对应文章的问题，不知道接下来该从哪个角度入手解决了。

点击各个页面的标签，Tag功能均无效。

**已经尝试过**

- [x] $ hexo new page tags 

- [x] 确认站点配置文件里有 tag_dir: tags 
- [x] 在主题配置文件里添加（本来没有） tags: /tags 
- [x] 编辑站点的source/tags/index.md，添加 

```
title: tags
date: 2015-10-20 06:49:50
type: "tags"
comments: false
```

均无效。

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**

- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

已部署上线的页面地址 https://lirenchong.com/

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**

- 部署的操作系统（OS）: Win10 专业版 64位
- $ hexo -v
	- hexo: 3.7.1
	- hexo-cli: 1.1.0
	- os: Windows_NT 10.0.16299 win32 x64
	- http_parser: 2.8.0
	- node: 10.5.0
	- v8: 6.7.288.46-node.8
	- uv: 1.20.3
	- zlib: 1.2.11
	- ares: 1.14.0
	- modules: 64
	- nghttp2: 1.32.0
	- napi: 3
	- openssl: 1.1.0h
	- icu: 61.1
	- unicode: 10.0
	- cldr: 33.0
	- tz: 2018c

和浏览器（Browser）无关：360极速浏览器，iPhone、Android都同样显示

**Comment by fi3ework** [comment]
你好，感谢使用，issue template 填的这么仔细很赞。
我看了一下你的 https://lirenchong.com/content.json，发现有 category 但是没有 tag 的属性。
是不是没有在文章的 markdown 中写 tag 的 front-matter 呢？
正确的姿势[如下](https://hexo.io/zh-cn/docs/front-matter.html)
![image](https://user-images.githubusercontent.com/12322740/42329542-79827b98-80a3-11e8-8d0d-23cdc4e39f91.png)

**Comment by fi3ework** [comment]
顺便说一句，archer 的 tag 用的不是 hexo 自带的那种方法，不需要额外配置 tags，只需按照文档中安装必要的插件再在文章中写 tag 的 front-matter 即可。

**Comment by lirenchong** [comment]
front-matter我应该有写的，按照[Front-matter](https://hexo.io/zh-cn/docs/front-matter.html) 这篇教程有尝试过并将所有_post的md文章都修改过了。

比如 [大脑认知资源限制与普遍的拖延](https://lirenchong.com/2018/07/05/2018-7-5%20GeneralProcrastination/)这一篇的设置如下。

---
title: 大脑认知资源限制与普遍的拖延
date: 2018-07-05 15:26:59
tags:
- 拖延
- 认知瘫痪
- GTD
- 时间管理
- 执行意图
- 番茄工作法
categories: 时计
header_image: http://pb2l0ws93.bkt.clouddn.com/lirenchong/180705/4DF3I0E2ga.jpg?imageslim

---

问题应该不是出在此处。

会不会是在部署环境、或安装hexo、或install archer时，有哪些地方出错了？

**Comment by fi3ework** [comment]
能提供一下 hexo 的 config 的 jsonContent 字段是怎么配置的吗

**Comment by lirenchong** [comment]
# 添加sidebar启用支持
jsonContent:
  meta: true
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: true
    excerpt: false
    categories: true
    tags: true

巧了，没看到你的消息，刚打开_config.yml里面就看到    
`tags: false`
改成true就好了

**Comment by lirenchong** [comment]
问题解决了，过程中学到了很多。谢谢～^ω^

**Comment by fi3ework** [comment]
是的，应该是 true 才对。应该直接从 archer 的文档中复制即可，文档中有配置的参数~

**Comment by fi3ework** [comment]
是的，应该是 true 才对。应该直接从 archer 的文档中复制即可，文档中有配置的参数~
