### ISSUE TITLE
很喜欢archer,非常棒,希望增加自定义功能

### ISSUE THREAD

**Issue by cellgit** [fi3ework/hexo-theme-archer#13]
希望增加自定义字段设置:
1.每个界面设置顶部的banner显示和隐藏
2.顶部的banner高度
3.底部上一篇和下一篇文章的切换更换成箭头或者枚举
因为很喜欢,所以希望能采纳建议,谢谢!

**Comment by fi3ework** [comment]
你好，感谢使用。
1. banner上承载了不少的信息（标题，副标题，tag，日期），如果取消了banner整体的界面就需要重新设计了，可能以后会做成像Next主题一样的几个子主题，但是在目前阶段这个不是很方便修改。
2. banner高度这个的修改我之后会在wiki里写。
3. 底部的切换的样式其实是仁者见仁智者见智了，如果想要改成自己想要的样子可以参照[二次开发文档](https://github.com/fi3ework/hexo-theme-archer/blob/master/docs/develop-guide.md)，修改`post.ejs`中的`post-pager`类和`_post-page.scss`中的样式，改成自己喜欢的样子。
再次感谢使用。
