### ISSUE TITLE
请问post的原文作者和原文链接在哪里修改？

### ISSUE THREAD

**Issue by fireflysao** [fi3ework/hexo-theme-archer#133]
![_ _20180710232556](https://user-images.githubusercontent.com/39042858/42520600-336475cc-8499-11e8-8008-d6c5e7c22861.png)

**Comment by fi3ework** [comment]
修改 [这几行](https://github.com/fi3ework/hexo-theme-archer/blob/98aa14a342481fcea9d26b653dfa5b9113176ab1/layout/post.ejs#L8-L11) 即可
