### ISSUE TITLE
Mathematical Expression Support

### ISSUE THREAD

**Issue by plzfday** [fi3ework/hexo-theme-archer#134]
I want to use "Latex" which can make me use mathematical expression. 
Hope I can use Latex with this theme.

**Comment by fi3ework** [comment]
hi, Of course you can use Latex with this theme, actually it's related to Hexo, not this theme.
You can get some help from this [artical](https://nathaniel.blog/tutorials/make-hexo-support-math-again/)

**Comment by plzfday** [comment]
thank you! I really appreciate your help 😁
