### ISSUE TITLE
本地和部署时显示的版权信息样式不同

### ISSUE THREAD

**Issue by secsilm** [fi3ework/hexo-theme-archer#135]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
在本地预览和发布到网站时文章最后显示的版权信息样式不同：

本地预览：

![](https://i.imgur.com/kwPnRfd.png)

部署后：

![](https://i.imgur.com/FENRkmM.png)

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
https://alanlee.fun/2018/07/14/remote-jupyter/

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**
![](https://i.imgur.com/icqPiz0.png)

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS] Windows 10
 - 浏览器（Browser） [e.g. chrome, safari] Chrome
 - 浏览器版本（Version）[e.g. 22][可选]  67.0.3396.99（正式版本） （64 位）

**其他信息（Additional context）**
主题是我今天（2018年7月14日）重新从 GitHub 上拉下来的，我把我原来的删了。

**Comment by fi3ework** [comment]
![image](https://user-images.githubusercontent.com/12322740/42722169-d04709e4-8779-11e8-89d9-73d37bf09b60.png)
看了下，你的 css 还是三个月前的，试一下先执行 `hexo clean`，再执行部署一下

**Comment by secsilm** [comment]
感谢感谢，果然是这个问题。
