### ISSUE TITLE
hexo编译静态网页错误

### ISSUE THREAD

**Issue by ToonoW** [fi3ework/hexo-theme-archer#14]
<img width="780" alt="default" src="https://user-images.githubusercontent.com/12607586/32098726-39a945d4-bb40-11e7-95f1-dbd1e3efee50.png">

我出现了以上的错误，错误文件是在layout那里，贴上来问问是不是跟主题有关

**Comment by fi3ework** [comment]
应该是主题配置文件里的about
字段被删掉了所以报错了，照原本主题的恢复一下
