### ISSUE TITLE
还有个问题😂--写个博客平滑更新的文档吧

### ISSUE THREAD

**Issue by hulichao** [fi3ework/hexo-theme-archer#140]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
今天想更新一下，楼主的新功能，发现我是看着git的提交记录改的，，，，，之前看到过，是吧config文件和文章备份就可以嘛？？？
**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [ ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [ ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by hulichao** [comment]
😂，，不好意思，问题有点多。

**Comment by fi3ework** [comment]
就是如何无痛升级吗

**Comment by hulichao** [comment]
嗯嗯，对滴

**Comment by hulichao** [comment]
是不是怎么都会痛，

**Comment by hulichao** [comment]
代码那个，我还是喜欢github的样式，所以我要自己重新改。

**Comment by hulichao** [comment]
哎。头疼的问题。

**Comment by hulichao** [comment]
好像没办法，，，只能这么痛

**Comment by hulichao** [comment]
复制时候的颜色，，感觉乖乖的。。。所以也改了，

**Comment by fi3ework** [comment]
可以倒是，pull 之后再重新生成主题，如果我和你改了相同的地方就得手动再解决冲突了
