### ISSUE TITLE
post_asset_folder 没有生成文件到目标目录

### ISSUE THREAD

**Issue by PopeyeZhong** [fi3ework/hexo-theme-archer#141]
在 hexo 站点的 _config.yml 中设置了 post_asset_folder: true 这个选项，然后使用 `hexo new test` 命令生成了一个文档（对应的文档目录`test`也成功生成），然后将一个名为 photo.jpg 图片文件拷贝到该目录中，接着在 test.md 中编辑如下内容后`：
```markdown
![tips](photo.jpg)
```
编辑保存后，使用 `hexo g` 生成，没有图片被拷贝到生成目标相关目录中，进行本地浏览该生成后的页面，也看不到图片内容。

**信息 (please complete the following information):**
 - 操作系统（OS）: Windows 10 x64 1803
 - 浏览器（Browser） chrome x64 v67
 - 浏览器版本（Version）67

**Comment by fi3ework** [comment]
这个并不是主题的问题，Hexo 中有提供正确的 [使用姿势](https://hexo.io/zh-cn/docs/asset-folders.html)

**Comment by PopeyeZhong** [comment]
对不起，是我的疏忽。
@fi3ework 
哈哈，我的博客站点开通起来了，我调整了下内容去的首行缩进，和导航指示器的字体。感觉还不错，老大去看看吧。另外，还是执念于“Titillium Web” 老大支持下吧。

[https://zongsoft.github.io/blog/zh-cn/misc/github-site](https://zongsoft.github.io/blog/zh-cn/misc/github-site)

**Comment by fi3ework** [comment]
😆字体不错，挺好看
