### ISSUE TITLE
为什么about页面的顶部图片没有链接

### ISSUE THREAD

**Issue by LtHugo** [fi3ework/hexo-theme-archer#145]
在.yml中的about enable有效 image设置了没反应  去到about页面调用的是post的layout

**Comment by fi3ework** [comment]
按照 [文档](https://github.com/fi3ework/hexo-theme-archer/wiki/%E5%90%AF%E7%94%A8about%E9%A1%B5) 操作的吗

**Comment by LtHugo** [comment]
嗯 按照文档操作的

在Hexo配置文件中添加以下字段，enable字段控制是否开启about，image字段内容为about页的banner图像地址，不填写则默认使用首页banner图像。

这里的Hexo配置文件 我在主题里面的yml设置enable就可以 image的链接没反应  在Hexo的yml设置不生效好像

**Comment by fi3ework** [comment]
不好意思，应该是在主题配置文件中修改 enable 和 image，文档不小心写错了。

**Comment by LtHugo** [comment]
呃....  可是配置里的image怎么不生效  其他配置的image都可以 就about这个不行

**Comment by fi3ework** [comment]
你的页面的 body 的属性不对，应该是下面的操作没有执行对
![image](https://user-images.githubusercontent.com/12322740/43580975-cce1200e-9689-11e8-9dfa-85ae68c41995.png)

**Comment by fi3ework** [comment]
缺了 `layout: about`

**Comment by LtHugo** [comment]
感谢！ 我太不小心了。
