### ISSUE TITLE
是否支持码云Gitee

### ISSUE THREAD

**Issue by XShandow** [fi3ework/hexo-theme-archer#148]
最近Github网速太慢，想用码云,项目复制之后，显示不正常，想问一下，是否支持Gitee.

**Comment by XShandow** [comment]
能帮我看一下吗，我F12看很多404
https://gitee.com/xshandow/1024Blog

https://xshandow.gitee.io/1024blog

在本地hexo server 是可以显示正常的，然后hexo d部署的

**Comment by fi3ework** [comment]
![image](https://user-images.githubusercontent.com/12322740/43989506-c83be368-9d7d-11e8-878b-f8f35452a80f.png)

如果没猜错的话，少了个路径 `/1024blog`，这应该是你 hexo 的 config 里的 root 没写成 `/1024blog` 的原因。

**Comment by XShandow** [comment]
嗯  谢谢了  是这个原因。
可以参考下http://git.mydoc.io/?t=154714
