### ISSUE TITLE
请问怎么才能增加latex公式支持啊

### ISSUE THREAD

**Issue by xtyDoge** [fi3ework/hexo-theme-archer#15]
自己试着装了hexo-math包,结果类似这种$Y=X^2$的公式没有渲染，$$Y=x^2$$这种的就变成了`<script type="math/tex; mode=display">J = 1/2m \sum_{i=1}^{m}[W^TX-Y]^2</script>`这个样的，在页面中没有显示。看到页面中也有引用Mathjax.js，不知道为什么会这样……求帮助

**Comment by fi3ework** [comment]
您好，我没有使用过Latex，查了一下，似乎Hexo对Latex的支持并不与主题相关。
你可以参照一下这篇文章，看看效果如何：[如何处理Hexo和MathJax的兼容问题](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/)。
后续如果有样式问题，我会进行修改。

**Comment by xtyDoge** [comment]
谢谢您，我已经解决这个问题啦~

**Comment by fi3ework** [comment]
😆不客气
