### ISSUE TITLE
建议加入分页

### ISSUE THREAD

**Issue by JianYu97** [fi3ework/hexo-theme-archer#151]
**提出你对主题的建议（Suggest your idea）**

**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**

**提出其他的你考虑到的点（Describe alternatives you've considered）**

**其他**
我觉得主题最好能接入分页，我现在写了几篇文章要拖到好长，我看是不是到10篇才会自动分页，能进行调整吗，还有能设置个目录这种吗，就是把文章进行归类，暂时就这些建议

**Comment by fi3ework** [comment]
1. 分页的页数设置在 hexo 的配置中有，默认是 10
2. 点击左上角的小图标了解一下？

**Comment by JianYu97** [comment]
ok，已经找到，还以为是主题设置，sorrysorrysorry
