### ISSUE TITLE
about 界面插入图片异常

### ISSUE THREAD

**Issue by Carrotor116** [fi3ework/hexo-theme-archer#152]
about 界面插入图片有异常。

在index.md同级目录的index文件夹下放置了about.jpg图片后，使用 `{% asset_path  about.jpg  %}`方式没有效果。使用markdown语法`![shamangirls.jpg](/intro/about.jpg)`能够出来图片，但是在界面上点击，没有和其他文章那边同样的预览效果。

README中[demo](http://firework.studio/archer-demo/)的about界面，也有同样的问题。

**信息: **
 - 操作系统（OS）: Windows 10 x64
 - 浏览器（Browser） Chrome 
 - 浏览器版本（Version）: 版本 68.0.3440.106（正式版本） （64 位）

**Comment by fi3ework** [comment]
这个并不是主题的问题哈，是你路径写的问题

**Comment by Carrotor116** [comment]
about.jpg 的路径是 `blog/source/about/index/about.jpg`，然后在 `blog/source/about/index.md`里写入`{% asset_img about.jpg %}`，不会显示图片。

_post文件夹内文章我使用这种方式写的，可以显示图片。

请问关于界面内插入图片，路径该怎样写呢？

**Comment by fi3ework** [comment]
我的 demo 中的图片是这样插入的，md 路径是 `source/about/index.md`，图片路径是 `source/about/index/b12.png`，md 中的引用是 `![b12](index/b12.png)`

**Comment by fi3ework** [comment]
问题已经了解，应该是以来的 fancybox 的配置问题，修复后 close，感谢回复~
