### ISSUE TITLE
畅言评论框不能正确显示

### ISSUE THREAD

**Issue by sdvdxl** [fi3ework/hexo-theme-archer#153]
集成畅言后，浏览到页面底部点击登录，出现了一层遮罩，但是看不见登录框，打开控制台后，发现是在页面的中上部导致没有显示出来。

**信息 (please complete the following information):**

userAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
🎯 hexo-theme-archer ⬇️ 
🏷 Version: 1.5.1 
📅 Version date: 20180811
 📦 https://github.com/fi3ework/hexo-theme-archer 
desktop
PLACEHOLDER REMOVED
font loaded
All resources finished loading!

暂时去掉了，替换为了其他

**Comment by fi3ework** [comment]
你好，畅言我是按照官网推荐的方法配置的，应该是主题的某些 css 影响了畅言的正确显示，但是安装畅言需要备案号...我这边没有备案，随意暂时无法解决这个 bug，推荐其他的评论系统，个人比较喜欢 livere，disqus 似乎会被墙。

**Comment by sdvdxl** [comment]
https://todu.top/posts/33607/#%E8%BF%9B%E9%98%B6 这是我的站点中的一篇文章，我又替换回到畅言了，你可以看一下页面上的问题。

**Comment by sdvdxl** [comment]
突然发现，右边的导航跟页面的标题显示有点误差，上面那个页面也能体现出这个问题
