### ISSUE TITLE
文章里图片左下角会显示一个null，在哪里可以设置这个？

### ISSUE THREAD

**Issue by Cherrs** [fi3ework/hexo-theme-archer#156]
![image](https://user-images.githubusercontent.com/6745593/44563304-3cae8680-a790-11e8-8eea-2265e1e7f4fb.png)

**信息 (please complete the following information):**
 - 操作系统（OS）: Windows 10 17134.228
 - 浏览器（Browser） Chrome
 - 浏览器版本（Version）68.0.3440.106

**其他信息（Additional context）**

**Comment by fi3ework** [comment]
这个是点了图片出来的 fancybox 吧，这个图是不是没有写 title，就类似 `[](./a.jpg)` 这样，所以是 null

**Comment by Cherrs** [comment]
用了官方的{% asset_img slug [title] %}
写了title 还是null 而且每一张都是null

**Comment by Cherrs** [comment]
用![](./a.jpg)可以显示

**Comment by Cherrs** [comment]
让{% asset_img slug [title] %}这个插件标签的title带到fancybox里？
