### ISSUE TITLE
某些文章日期不能正确显示

### ISSUE THREAD

**Issue by zhihaozhang** [fi3ework/hexo-theme-archer#159]
![](https://ws3.sinaimg.cn/large/006tNbRwgy1fuky9ulthej30l20iqt9i.jpg)

我的博客: http://zhihaozhang.github.io/

点击左上角的 > (blog列表)按钮后，有些文章日期显示为Invalid date

**Comment by zhihaozhang** [comment]
但是在文章内部，合法解析出来了。

**Comment by fi3ework** [comment]
可以在这里贴一下 markdown 里的日期的部分，我看下

**Comment by fi3ework** [comment]
seems it has been reolved

**Comment by XDMonkey** [comment]
发现还有这个问题。。。zhihaozhang的链接中还是有这样的问题

**Comment by XDMonkey** [comment]
我的也有这样的问题

**Comment by fi3ework** [comment]
可以贴一下
`是因为自己在文章标题部分没有写日期，不过为什么有的可以解析，` 这两个的 md

**Comment by ZerGen** [comment]
遇到了相同问题，不知道如何解决，部分文章日期显示正常，部分显示非法日期。
