### ISSUE TITLE
MD排序识别有问题

### ISSUE THREAD

**Issue by qq729556278** [fi3ework/hexo-theme-archer#160]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
1. 博客或日志中，如果上一级使用了数字排序如“1. ”，“2. ”，而他的下级使用无序排序“*”，则无序排序会被认为是数字排序，反之亦然
2. 提一点建议，个人认为在数字排序中，个位数在前面补0的做法并不美观

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**
![](https://ws1.sinaimg.cn/large/5e86e3a4gy1fuoe4495axj21ku0jowlo.jpg)

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
https://139.199.80.79/posts/ff96664.html#%E5%88%9B%E5%BB%BA%E5%AE%9E%E4%BE%8B

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**
```markdown
2. 通过`创建实例`或者单击加号来创建一个虚拟机。

   * 名称：随意输入

   * 区域：建议选择asia-east1（台湾）

   * 地区：建议选择asia-east1-c
```

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**
最新版本

**信息 (please complete the following information):**
 - 操作系统（OS）: MacOS 10.13.6
 - 浏览器（Browser）:chrome
 - 浏览器版本（Version）:版本 68.0.3440.106（正式版本） （64 位）

**其他信息（Additional context）**

**Comment by fi3ework** [comment]
问题大概清楚了，不过提供的链接打不开啊 😅

**Comment by qq729556278** [comment]
域名在做备案，暂时把解析关了，已经更新了地址，现在可以看了
https://139.199.80.79/posts/ff96664.html#%E5%88%9B%E5%BB%BA%E5%AE%9E%E4%BE%8B

**Comment by qq729556278** [comment]
那这个0的问题我再自己检查一下😂
