### ISSUE TITLE
@babel/core 已经更新至7.0.1版本 现在build会报错

### ISSUE THREAD

**Issue by piexlmax** [fi3ework/hexo-theme-archer#166]
@babel/core 已经更新至7.0.1版本 现在build会报错

**Comment by piexlmax** [comment]
> @babel/core 已经更新至7.0.1版本 现在build会报错

不是报错，是编译完的版本 生成的文件使用的时候会报错

**Comment by nnkwrik** [comment]
编译完成后，server启动时会报错。有什么办法吗？

**Comment by fefz** [comment]
我也遇到了，你是不是node10？
