### ISSUE TITLE
打开文章界面空白

### ISSUE THREAD

**Issue by LibraTang** [fi3ework/hexo-theme-archer#168]
**打开文章界面空白**

**存在问题或 bug 的已部署上线的页面地址（https://libratang.github.io/）**

**信息 (please complete the following information):**
 - 操作系统（OS）: Windows10
 - 浏览器（Browser） chrome

**Comment by fi3ework** [comment]
`hexo g` 出来的文章也就就是空的
https://github.com/LibraTang/LibraTang.github.io/blob/master/2018/09/19/Java%E5%9F%BA%E7%A1%80%E7%AC%94%E8%AE%B01%EF%BC%9A%E7%B1%BB%E4%B8%8E%E5%AF%B9%E8%B1%A1/index.html
应该是 hexo 的配置的问题

**Comment by LibraTang** [comment]
> `hexo g` 出来的文章也就就是空的
> https://github.com/LibraTang/LibraTang.github.io/blob/master/2018/09/19/Java%E5%9F%BA%E7%A1%80%E7%AC%94%E8%AE%B01%EF%BC%9A%E7%B1%BB%E4%B8%8E%E5%AF%B9%E8%B1%A1/index.html
> 应该是 hexo 的配置的问题

更换主题后文章显示正常，应该不是hexo配置问题吧。

**Comment by fi3ework** [comment]
可以先换个主题试一下会不会还是空白的

**Comment by gjgjh** [comment]
遇到了同样的问题，不知道怎么解决

**Comment by gjgjh** [comment]
> > 可以先换个主题试一下会不会还是空白的
> 
> 换了一个主题，打开是正常显示。

你少装东西了，安装下面命令后再重新试试
npm i --save hexo-wordcount

**Comment by devilvalley** [comment]
我也是打开空白，楼主解决了没有

**Comment by Spoience** [comment]
> > > 可以先换个主题试一下会不会还是空白的
> > 
> > 
> > 换了一个主题，打开是正常显示。
> 
> 你少装东西了，安装下面命令后再重新试试
> npm i --save hexo-wordcount

按照这个解决了，非常感谢
