### ISSUE TITLE
关于algolia无法使用站内搜索

### ISSUE THREAD

**Issue by ROTblog** [fi3ework/hexo-theme-archer#171]
$ export HEXO_ALGOLIA_INDEXING_KEY=‘xxxxxxxxxxxxxxxx’
$ hexo algolia
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'filter' of undefined
然后就报错了，怎么解决这个问题

**Comment by FaithGit** [comment]
> 是windows还是mac

我设置完了，并没有找到搜索框

**Comment by fi3ework** [comment]
在侧边栏里。
另外还要在配置中启用
```yaml
algolia_search:
  enable: true
```

**Comment by FaithGit** [comment]
> 在侧边栏里。
> 另外还要在配置中启用
> 
> ```yaml
> algolia_search：
>    enable：true
> ```

已经开启了，F12 找到这个元素  height 为0   我看到有些人说z-index 9999太大了 改小了 也没有用

**Comment by FaithGit** [comment]
> 在侧边栏里。
> 另外还要在配置中启用
> 
> ```yaml
> algolia_search:
>   enable: true
> ```

找到了！大佬建议
1.搜索再醒目点
2.侧边栏 > 加个触发收回

**Comment by fi3ework** [comment]
确实值得
