### ISSUE TITLE
关于「不蒜子」阅读统计失效的解决方法

### ISSUE THREAD

**Issue by I-mpossible** [fi3ework/hexo-theme-archer#172]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
访问量统计突然没了
**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**
不清楚，我觉得可能是我装了hexo博文加密插件的原因？这个插件反正用起来是有点问题，会让加密博文的最上面header那的字体变小
![360 20181008201011953](https://user-images.githubusercontent.com/26900284/46608118-37d24600-cb36-11e8-8aa4-cb1d8a952fe9.png)
![360 20181008201339599](https://user-images.githubusercontent.com/26900284/46608242-ae6f4380-cb36-11e8-97d3-a674680c7273.png)

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]ubuntu 16.04
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by fi3ework** [comment]
现在统计的 14 是你加密后的字数吧

**Comment by secsilm** [comment]
我也遇到了，前两天还能看到的，今天看了一下不行了。[我的页面](https://alanlee.fun/)：

![](https://i.imgur.com/zsX6ATo.png)

控制台信息：

![](https://i.imgur.com/QvSZQKt.png)

**Comment by I-mpossible** [comment]
> 现在统计的 14 是你加密后的字数吧

不是，这篇的截图没有加密，而且我已经把加密关了还是这样，这篇就这几个字。我说的是那个有多少人看过这篇的统计看不到了，

**Comment by fi3ework** [comment]
@I-mpossible @secsilm 
统一回复：是不蒜子换了链接，更新最新版本的主题即可。
或者不想更新最新版本，可以手动修改不蒜子的链接地址，参考 [pr](https://github.com/fi3ework/hexo-theme-archer/pull/175/files)

**Comment by imkangkang** [comment]
@fi3ework ，谢谢，问题已解决

**Comment by threst** [comment]
谢谢，问题已解决
