### ISSUE TITLE
无法解析句子或段落中的```  ```

### ISSUE THREAD

**Issue by bryanibit** [fi3ework/hexo-theme-archer#173]
如果段落中有```content```，这时hexo无法解析，而另起一段则hexo可以解析3个`为code style类型，不知道这个需要在config中添加什么命令？急求！谢谢

**Comment by fi3ework** [comment]
content 是什么意思啊

**Comment by bryanibit** [comment]
就是说如果使用两个\'''，期望得到code style的效果，但是没有换行，这时这两个\'''无法解析，会在解析后的html中原模原样的显示。如果在两个\'''前后加上换行，则code style 显示正常。

**Comment by fi3ework** [comment]
按照 md 的语法就是应该加回车的

**Comment by bryanibit** [comment]
就像[这个一样](https://bryanibit.github.io/blog/2018/09/28/effective-cpp/#decltype-type) myWidget也是三个'的效果

**Comment by fi3ework** [comment]
没太明白什么意思。。

**Comment by bryanibit** [comment]
以上是使用jekyll的结果，而使用hexo的时候上面的myWidget前后的'''无法解析！

**Comment by fi3ework** [comment]
这并不是主题的问题啊，是因为 hexo 的 markdown 解释器并没有 jekyll 好，目前 archer 用的还是 hexo 自带的 md 解释器，所以解决方法就是尽量按照规范的 md 语法写。
