### ISSUE TITLE
multiple category hierarchies not working 

### ISSUE THREAD

**Issue by theJiawen** [fi3ework/hexo-theme-archer#179]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**

多层的 category 点击后无法正确筛选.

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**

- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

在某个 post 的 meta 数据的 categories 写一个多层的category
```md
categories: 
- [Foo, Bar, Baz]
```

这时点击 sidebar 的 category 一栏的 tag, 只有第一个 'Foo' 能点击, 第二层的 'Foo/Bar' 和 第三层的 'Foo/Bar/Baz' 均无法点击.(点击后无筛选作用)

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

官方demo
http://firework.studio/archer-demo/2013-12-24/categories/

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

![image](https://user-images.githubusercontent.com/16242633/47629504-70ce6b00-db76-11e8-90cc-f999b1265dda.png)

**其他信息（Additional context）**
我已经 fix 了, 准备发一个PR :D

**Comment by LolipopJ** [comment]
感谢贡献！😄
