### ISSUE TITLE
"Next Post" 和 "Previous Post" 按钮的文字颠倒了.

### ISSUE THREAD

**Issue by guanrongYang** [fi3ework/hexo-theme-archer#184]
"Next Post" 和 "Previous Post" 按钮的文字颠倒了.

**Comment by guanrongYang** [comment]
而且如果多篇文章使用了相同的时间, 如多篇文章的date为2018-11-04,则翻页功能和侧边的Archive的顺序会有所不同也.

**Comment by bjio** [comment]
1. 定位到：archer/layout/post.ejs 
2. 查找：prevSlogan，nextSlogan
3. `<div class="nextSlogan">Previous Post</div>` 与 `<div class="prevSlogan">Next Post</div> `调换位置
---
进一步修改可以把类名也改了
1. 定位：archer/source/css/style.css
2. 查找: prevSlogan，同理调换两个类名

**Comment by Sciroccogti** [comment]
> "Next Post" 和 "Previous Post" 按钮的文字颠倒了.

其实感觉目前的思路是对的耶，新文章在左侧，旧文章在右侧
