### ISSUE TITLE
添加了 404.md 没反应

### ISSUE THREAD

**Issue by Han-MeiM** [fi3ework/hexo-theme-archer#185]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
![image](https://user-images.githubusercontent.com/27951114/48242993-c75e6380-e418-11e8-8dda-af27e3c29e29.png)
已经在 `source` 中添加了 404.md 但是并没有效果
![image](https://user-images.githubusercontent.com/27951114/48243006-de9d5100-e418-11e8-8358-8d8fe3bcf23d.png)

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: mac
 - 浏览器（Browser） chrome
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by LolipopJ** [comment]
好耶！😋
