### ISSUE TITLE
如何在主题中使用markdown的流程图

### ISSUE THREAD

**Issue by Stefankeep** [fi3ework/hexo-theme-archer#186]
### 使用环境
node v10.12.0
yarn 1.10.1
hexo 3.8.0

### 出现问题

+ hexo-filter-mermaid-diagrams提示的问题无法渲染
+ hexo-filter-flow可以使用，但是官方的都渲染失败，图形错乱

### 希望
作者能推荐一个可以在archer主题下可以使用的流程图插件嘛

**Comment by Sciroccogti** [comment]
可以尝试在本地先编译为`.html`后，上传`.html`而不是`.md`。

当然这只是曲线救国。。
