### ISSUE TITLE
在macOS 10.14+的Chrome中，在首页的文章摘要内容的字体过细

### ISSUE THREAD

**Issue by vsxd** [fi3ework/hexo-theme-archer#189]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
在主页中显示的文章摘要内容中。非英文字体过细，在英文字体正常的对比下十分明显。
![img](https://ws4.sinaimg.cn/large/006tNbRwgy1fxnt5cxvymj315z0u0asd.jpg)
![img](https://ws3.sinaimg.cn/large/006tNbRwgy1fxnt787czij31c80a841t.jpg)
macOS升级10.14后chrome中的字体普遍变细，加上主题中又使用了`font-weight: lighter;`，结果导致了在chrome下字体过细。

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [ ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [ ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

打开使用了本主题的博客主页，在macOS 10.14+ Mojave操作系统上Chrome浏览器中即可稳定复现。

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

任意已上线的页面，包括[Demo页面](http://firework.studio/archer-demo/) 和[我的博客](https://xudong07.github.io/)

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**
```bash
➜  hexo version                                                            [aed9e62]
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
http_parser: 2.8.0
node: 11.2.0
v8: 7.0.276.38-node.11
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

**信息 (please complete the following information):**
 - 操作系统（OS）: macOS 10.14.1
 - 浏览器（Browser）: Chrome
 - 浏览器版本（Version）: Version 70.0.3538.110 (Official Build) (64-bit)

**其他信息（Additional context）**

**Comment by Wrapperss** [comment]
我也遇到了同样的情况

**Comment by LolipopJ** [comment]
很抱歉，由于此 Issue 已经开启很一段时间了，我将关闭此 Issue 🗃。如果有更多问题，请重新打开它！
