### ISSUE TITLE
Disqus 無法加載

### ISSUE THREAD

**Issue by aszx4510** [fi3ework/hexo-theme-archer#19]
作者您好，
我直接在主題的 _config.yml 中加入 disqus_shortname 卻出現加載失敗，
根據[官方](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22)的建議，`this.page.url` 要設定成絕對路徑才行，

目前我暫時將`disqus.ejs`修改為
`this.page.url = "http://aszx4510.github.io<%- url_for(page.path) %>";`
目前可以[正常運作](https://github.com/aszx4510/aszx4510.github.io/commit/61f46723f7ccc0898dfc8b3aac8a555b3503a544)了，可以參考[我的blog](https://aszx4510.github.io/2017/11/19/captcha-recognition/)，
但這方法只是暫時的，
小弟我不熟 javascript，沒辦法幫忙修正，
麻煩你改為正確的語法囉 :D

**Comment by fi3ework** [comment]
您好。
我又测试了一下disqus的功能，在为[相对路径](https://github.com/fi3ework/archer-demo/blob/gh-pages/2013-12-30/%E4%B8%AD%E6%96%87%E6%B8%AC%E8%A9%A6/index.html#L236)的时候，也是可以正常显示的（[链接](http://firework.studio/archer-demo/2017-08-14/hexo-theme-archer/)）（至少在我这里测试是可以）。
所以，我这里暂时无法复现您说的bug，我能想到几个点
1. disqus加载失败具体是指什么呢，是disqus加载出来了但是路径不匹配吗
2. 请确认一下disqus的配置是正确的
3. 请确认一下主题config文件里的`url`和`root`填写正确

再次感谢使用:smile:

**Comment by aszx4510** [comment]
> 我又测试了一下disqus的功能，在为[相对路径](https://github.com/fi3ework/archer-demo/blob/gh-pages/2013-12-30/%E4%B8%AD%E6%96%87%E6%B8%AC%E8%A9%A6/index.html#L236)的时候，也是可以正常显示的（[链接](http://firework.studio/archer-demo/2017-08-14/hexo-theme-archer/)）（至少在我这里测试是可以）。

你這段 code 仍然是絕對路徑吧?

根據 [github 的紀錄](https://github.com/aszx4510/aszx4510.github.io/commit/61f46723f7ccc0898dfc8b3aac8a555b3503a544#diff-7163b1faea0a3ef97b62cb1bc6d5f6acL243)，相對路徑和絕對路徑分別是下面兩種形式，

`this.page.url = "/2017/11/19/captcha-recognition/";`
`this.page.url = "http://aszx4510.github.io/2017/11/19/captcha-recognition/";`

下面回答你的問題~
1. 加载失败具体是指什么呢，是disqus加载出来了但是路径不匹配吗
`加載失敗`就是disqus顯示的錯誤訊息，
我暫時沒辦法重現這個bug，因為存放原始碼的電腦不在我身邊，
用google也沒有找到類似的圖片給你參考
或許你把`page.url`改成相對路徑試試看?
`this.page.url = "http://fi3ework.github.io/archer-demo/2013-12-30/中文測試/";`
`this.page.url = "/archer-demo/2013-12-30/中文測試/";`
1. 请确认一下disqus的配置是正确的
disqus的設定應該是沒問題的，
因為我改了`page.url`後就可以正常使用了。
1. 请确认一下主题config文件里的`url`和`root`填写正确
_config.yml 檔案中，
`url: http://aszx4510.github.io`
`root: /`
這樣應該沒問題吧?

感謝你的迅速回覆 :D

**Comment by fi3ework** [comment]
问题找到了，确实是相对路径的问题。
我上午的时候说相对路径也可以，确实是也可以。你现在点一下我上午给你发的链接，代码里是相对路径的，disqus也能加载。但是玄学的是，除了第一篇文章，其他文章的disqus都不能加载-_-，并且并不是因为它是第一篇所以可以加载，我新写了一篇post，新的post也不能加载，还是只有它能。不想追究这个玄学问题了，一会儿我就把它改成绝对路径。
非常感谢发现这个bug~
