### ISSUE TITLE
如何修改github图标的地址？

### ISSUE THREAD

**Issue by o0foam** [fi3ework/hexo-theme-archer#192]
我想把github的地址换成自己的，但是却找不到在哪里配置。可以告诉我吗

**Comment by secsilm** [comment]
参见 [README 中的主题配置部分](https://github.com/fi3ework/hexo-theme-archer#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE)，就是在 `_config.yml` 中修改 `github` 项。
