### ISSUE TITLE
不蒜子 首页统计失效的解决方法

### ISSUE THREAD

**Issue by FaithGit** [fi3ework/hexo-theme-archer#194]
在layout/_partial/base-footer.ejs 文件下

![image](https://user-images.githubusercontent.com/19992034/50267896-ca129680-0463-11e9-8fc1-c0a19a9a7b50.png)

呈现的效果将是
![image](https://user-images.githubusercontent.com/19992034/50267764-4b1d5e00-0463-11e9-914a-a3f6b6775f26.png)

所以直接用不蒜子统计UA访问量的方式替换

![image](https://user-images.githubusercontent.com/19992034/50268100-718fc900-0464-11e9-80e8-851a7137e8fa.png)

![image](https://user-images.githubusercontent.com/19992034/50267804-6c7e4a00-0463-11e9-9a3e-17335a7340b4.png)

样式修改因为水平不足，不太理解怎么修改，希望诸位大大能够修改一下这个简单的样式让它变的archer风~

**Comment by CCChenhao997** [comment]
同问

**Comment by LolipopJ** [comment]
可以在 Console 处检查 busuanzi 是否拉取成功。另外，可以参考我的 [此回答](https://github.com/fi3ework/hexo-theme-archer/issues/282#issuecomment-875225989)。

如果没有更多问题，我将关闭此 Issue，感谢您的理解！😄
