### ISSUE TITLE
插入视频（html代码）被渲染成文本

### ISSUE THREAD

**Issue by LAOFeng** [fi3ework/hexo-theme-archer#195]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
插入视频（html代码）被渲染成文本
**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by LolipopJ** [comment]
Markdown 文档的解析由 Hexo 提供，在默认情况下是 [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)。而它在默认情况下不支持视频文件的解析。

您可以通过以下方法添加视频文件：

- 使用 HTML 的 <iframe> 标签。Markdown 解析器将直接将它作为 HTML 元素，而跳过解析。
- 使用 Hexo 解析增强插件。例如 [hexo-tag-bilibili](https://github.com/Z4Tech/hexo-tag-bilibili)，[hexo-tag-video](https://github.com/geekplux/hexo-tag-video) 等。它们都具有特定的 Markdown 标签编写格式，应参考文档使用。
