### ISSUE TITLE
文章版权信息的修改

### ISSUE THREAD

**Issue by yearing1017** [fi3ework/hexo-theme-archer#196]
大佬。。。怎么修改文章后面的版权信息啊。。。小白找不到

**Comment by czorange123** [comment]
https://github.com/fi3ework/hexo-theme-archer/wiki/%E8%AE%BE%E7%BD%AE%E6%96%87%E7%AB%A0%E7%89%88%E6%9D%83%E4%BF%A1%E6%81%AF
