### ISSUE TITLE
老铁，我想知道这个是不是用了自己的滑动条？因为我用起来没有其他普通页面流畅

### ISSUE THREAD

**Issue by ToonoW** [fi3ework/hexo-theme-archer#2]
主要原因是页面不太流畅，有那种玩3D游戏帧率跟不上的感觉。

我不确定是不是因为自动出现隐藏的导航条导致的。

**Comment by ToonoW** [comment]
希望有个设置能够开启和禁用自动出现和隐藏的导航条效果。

**Comment by fi3ework** [comment]
老铁，不知道你说的是主页还是文章页帧率跟不上呢？我用chrome的帧率监测文章页有60fps，首页的话有50fps（可能首页过于频繁触发重排了，我再看下）

**Comment by ToonoW** [comment]
我就是Mac chrome文章页比较不流畅，特别是导航栏出现或者隐藏那个时刻。因为文章不长，所以导航栏的动画比较频繁。

我用Safari倒是如丝顺滑。
可能是我的chrome猫病？

附上我觉得体验不好的[一页](http://toonow.coding.me/2017/08/26/%E8%B8%A9%E8%BF%87%E6%89%8D%E7%9F%A5%E9%81%93%E7%9A%84Django%E5%9D%91/)

**Comment by fi3ework** [comment]
我也是在Mac下测试的，用chrome测试了一下你的页面有55fps左右（而且说实话没感到有卡顿😅）。我刚才看了下代码，初步确定是sidebar的滚轮的事件触发太频繁了，我把那块代码注释了测试，即使在频繁显示隐藏导航栏的情况下也是60fps，这个问题我会尽快修复。
换句话说，你试试用触摸板的双指滑动呢，这样不会触发滚轮事件，还会感到卡顿吗。

**Comment by fi3ework** [comment]
修改了背景图像的占位符的播放次数，我本地测试已经都是60fps了，老铁pull一下试试效果😀

**Comment by ToonoW** [comment]
好多了，感谢老铁

**Comment by fi3ework** [comment]
😀感谢老铁使用
