### ISSUE TITLE
怎么添加内部搜索功能

### ISSUE THREAD

**Issue by ciweigg** [fi3ework/hexo-theme-archer#20]
怎么添加内部搜索功能，和为什么我
![image](https://user-images.githubusercontent.com/31340264/33813430-b2d58cc4-de5e-11e7-81e1-ca1a6cce3a08.png)内容详情b不显示了

**Comment by fi3ework** [comment]
1. 搜索功能暂时没有，网上有很多方法添加可以搜索一下。
2. 内容显示不了是不是因为把主题的config中的`truncate_length:`设为0了呢

**Comment by DomBro96** [comment]
请问为什么我点击左侧Tag下面的标签，不显示相应文章？

**Comment by fi3ework** [comment]
@DomBro96 
你好，可以先参照[这个issue](https://github.com/fi3ework/hexo-theme-archer/issues/18#issuecomment-347432307)看一下

**Comment by DomBro96** [comment]
好了，谢谢，自己瞎调把 pages 设成 true 了，很喜欢你主题的风格简单大气

**Comment by ciweigg** [comment]
![image](https://user-images.githubusercontent.com/31340264/33830949-2beea77e-deb1-11e7-8813-d935528edbd3.png)
默认300 我开始是没写的 现在写了300还是不显示

**Comment by fi3ework** [comment]
@ciweigg 
这个我也不太清楚，也没遇到过，我觉得可能是hexo的问题吧，可以重新安装或升级一下hexo。如果修改过主题的话重新再下载一次

**Comment by ciweigg** [comment]
重新安装过你的主题了，也不显示，难道是我安装了admin后台了？

**Comment by fi3ework** [comment]
什么东西的admin后台，我推测主要的原因可能是hexo，我的hexo版本是3.3.8

**Comment by ciweigg** [comment]
Hexo的admin 怎么更新hexo 我第一次安装好显示的呀

**Comment by fi3ework** [comment]
hexo的admin是什么啊。。不是按照官网的那样用npm安吗
