### ISSUE TITLE
好喜欢第一个版本的所有banner图片，可惜图床链接都失效了 TAT

### ISSUE THREAD

**Issue by warmilk** [fi3ework/hexo-theme-archer#205]
就是这个版本的banner图，有小男孩趴着的壁画的，大大还能再提供一份嘛，chrome缓存里找了好久还是找不回来。。

# site haeder image
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

**Comment by warmilk** [comment]
求大大甩图。。这个版本的banner图。。

![go](https://user-images.githubusercontent.com/14016918/51841662-21046900-234a-11e9-92aa-ddf6af636878.PNG)

**Comment by warmilk** [comment]
post haeder image QAQ

**Comment by Boycottangent** [comment]
如果只是这张图的话 https://unsplash.com/photos/eIhH7RTlTZA

**Comment by warmilk** [comment]
阿里嘎多！
