### ISSUE TITLE
categories二级分类无效

### ISSUE THREAD

**Issue by MrASDB** [fi3ework/hexo-theme-archer#209]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
在文章头部添加类似以下内容对文章进行分类，博客主页左边菜单栏cate中会有“极客”，“极客/Hexo”两个标签，点击“极客”会显示对应文章，但点击“极客/Hexo”则无效
```markdown
categories:
- 极客
- Hexo
```
**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**
在文章头部添加二级分类
```
categories:
- 极客
- Hexo
```
**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
http://firework.studio/archer-demo/
**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**
v0.1.5
**信息 (please complete the following information):**
 - 操作系统（OS）: windows10
 - 浏览器（Browser）:chrome
 - 浏览器版本（Version）版本 72.0.3626.119 (正式版本) (64 位元)

**其他信息（Additional context）**
查看Hexo的db.json文件以及默认的landscape主题，发现当使用二级分类时，存储格式不是“一级分类/二级分类”，而是直接使用“二级分类”，所以导致``data-categories="<%- category.slug %>"``无法找到正确的文章，临时的解决办法是直接修改"\themes\archer\layout\_partial\sidebar\sidebar-categories.ejs"中的``data-categories="<%- category.slug %>"``为``data-categories="<%- category.name %>"``

**Comment by mrh929** [comment]
感谢提供issue解决方案的大大！ 我也遇到这个问题了 成功解决！

**Comment by JTongChen** [comment]
请问，若用的是chic主题，该如何解决上面的问题呢？
