### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by zjw-zjw** [fi3ework/hexo-theme-archer#211]
我按照你的方法设置了，但是主题还是没变，请问是什么问题呢？-。-

**Comment by Sciroccogti** [comment]
请再次尝试设置，并仔细阅读[Hexo 文档](https://hexo.io/zh-cn/docs/)

我就是按照教程走的，没有问题呢~

**Comment by zjw-zjw** [comment]
> 
> 
> 请再次尝试设置，并仔细阅读[Hexo 文档](https://hexo.io/zh-cn/docs/)
> 
> 我就是按照教程走的，没有问题呢~

谢谢你~我弄好了
