### ISSUE TITLE
站内搜索生成静态文件报错，大佬帮忙看下

### ISSUE THREAD

**Issue by AllensLeng** [fi3ework/hexo-theme-archer#212]
![image](https://user-images.githubusercontent.com/40853659/55068784-96c45100-50bd-11e9-8ff2-b9ffe1d6e65e.png)

**Comment by LolipopJ** [comment]
这可能是您的 `_config.yml` 文件中存在重复的配置字段导致的。

考虑到此 Issue 已经发布很久了，我将暂时关闭此 Issue，如果您仍有问题或新的麻烦，欢迎重新打开！😄
