### ISSUE TITLE
如何为一片文章增加多个tag

### ISSUE THREAD

**Issue by Attriumph** [fi3ework/hexo-theme-archer#213]
同一文章如何增加多个tag？

在文章的md文档中tags写多个tag，不会显示出来，请问如何显示多个tag呢？

**Comment by 1172100327** [comment]
请问你知道怎么添加了吗，另外有一个问题，最后一项cate是什么意思

**Comment by Attriumph** [comment]
> 请问你知道怎么添加了吗，另外有一个问题，最后一项cate是什么意思

写上front matter就可以啦，[看这里就都知道了～](https://hexo.io/docs/front-matter.html)

**Comment by 1172100327** [comment]
> 请问你知道怎么添加了吗，另外有一个问题，最后一项cate是什么意思
> 
> 写上front matter就可以啦，看这里就都知道了～

多谢

**Comment by Attriumph** [comment]
> > 请问你知道怎么添加了吗，另外有一个问题，最后一项cate是什么意思
> > 写上front matter就可以啦，看这里就都知道了～
> 
> 多谢

客气
