### ISSUE TITLE
代码块导致页面加载不出来

### ISSUE THREAD

**Issue by yongwuzhijin** [fi3ework/hexo-theme-archer#216]
![image](https://user-images.githubusercontent.com/24710329/55673702-ebe23d00-58dd-11e9-861c-741194dd4629.png)
上图格式代码，也没加载不出来，控制台无报错信息。

![image](https://user-images.githubusercontent.com/24710329/55673716-1502cd80-58de-11e9-85ed-bc8e1ce11422.png)
这样页面正常加载

更奇怪的是把上面一个代码块删了也就正常加载

**Comment by LolipopJ** [comment]
输入：

```
    ```
    plugins = (
      git
      incr
      zsh-autosuggestions
      zsh-syntax-highlighting
    )
    ```
```

![屏幕截图 2021-08-24 175130](https://user-images.githubusercontent.com/42314340/130596392-e8624add-666c-4e58-8c62-d13557b95ad1.png)

目前一切工作正常。

引发这个问题的最大可能原因是 MD 解析器出现了 BUG，与本主题无关。可以尝试更新 Hexo 的 MD 渲染引擎到最新版本。

此 Issue 开启时间很久了，我将关闭它 🌺。如果有更多问题欢迎重新打开！
