### ISSUE TITLE
如何在文章目录页显示图片，请求帮助！

### ISSUE THREAD

**Issue by JunqiFu** [fi3ework/hexo-theme-archer#224]
**「如何在文章目录页显示图片」**
    像这样，如何在首页，让文章的目录页显示图片

![001](https://user-images.githubusercontent.com/34265930/58448096-56bf3000-8139-11e9-98e5-b68e24f38786.jpg)

 我的样子：
  
![image](https://user-images.githubusercontent.com/34265930/58448193-ac93d800-8139-11e9-9f85-160f30d8f4d9.png)

**信息 (please complete the following information):**
 - 操作系统（OS）: [ window10 ]
 - 浏览器（Browser） [ chrome ]
 - 浏览器版本（Version）[ 版本 74.0.3729.169（正式版本）]

**其他信息（Additional context）**

作者的主题非常棒，非常感谢作者
[我的博客地址](https://junqifu.github.io/)

**Comment by ddgth** [comment]
> **「如何在文章目录页显示图片」**
> 像这样，如何在首页，让文章的目录页显示图片
> 
> ![001](https://user-images.githubusercontent.com/34265930/58448096-56bf3000-8139-11e9-98e5-b68e24f38786.jpg)
> 
> 我的样子：
> 
> ![image](https://user-images.githubusercontent.com/34265930/58448193-ac93d800-8139-11e9-9f85-160f30d8f4d9.png)
> 
> **信息 (please complete the following information):**
> 
> * 操作系统（OS）: [ window10 ]
> * 浏览器（Browser） [ chrome ]
> * 浏览器版本（Version）[ 版本 74.0.3729.169（正式版本）]
> 
> **其他信息（Additional context）**
> 
> 作者的主题非常棒，非常感谢作者
> [我的博客地址](https://junqifu.github.io/)

同求这个问题。 感觉和置顶有关。

**Comment by ddgth** [comment]
> **「如何在文章目录页显示图片」**
> 像这样，如何在首页，让文章的目录页显示图片
> 
> ![001](https://user-images.githubusercontent.com/34265930/58448096-56bf3000-8139-11e9-98e5-b68e24f38786.jpg)
> 
> 我的样子：
> 
> ![image](https://user-images.githubusercontent.com/34265930/58448193-ac93d800-8139-11e9-9f85-160f30d8f4d9.png)
> 
> **信息 (please complete the following information):**
> 
> * 操作系统（OS）: [ window10 ]
> * 浏览器（Browser） [ chrome ]
> * 浏览器版本（Version）[ 版本 74.0.3729.169（正式版本）]
> 
> **其他信息（Additional context）**
> 
> 作者的主题非常棒，非常感谢作者
> [我的博客地址](https://junqifu.github.io/)
这里有解决办法 我是用的 截断可以了
[https://segmentfault.com/q/1010000004840061](url)

**Comment by JunqiFu** [comment]
感谢，已解决
参考答案：
```
这个直接用markdown编辑就可以吧，图片指令，如果想要图片在摘要显示的话这样：

这里显示图片

<!--more-->

这里是全文
```
效果：
![image](https://user-images.githubusercontent.com/34265930/59003675-852fc000-8849-11e9-8e9a-866ff7739a93.png)
