### ISSUE TITLE
按照教程配置完algolia后页面没有变化

### ISSUE THREAD

**Issue by ddgth** [fi3ework/hexo-theme-archer#226]
按照教程配置完algolia后页面没有变化

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by LolipopJ** [comment]
在以前的版本中，Algolia 的 .ejs 文件存在编码错误，导致无法渲染。

在目前的版本中，如果配置成功，Algolia 的搜索按钮放置在侧边栏 Archive 的 Total 右侧。

您可以通过右键单击网页 - 检查 - 在 Console 处查看 Algolia 是否配置成功。

说实话按钮的位置并不直观，在未来的版本更新中，我们或许会将搜索按钮放在页面顶部部分。

如果没有更多问题，我将关闭此 Issue，感谢您的理解！😄
