### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by microvorld** [fi3ework/hexo-theme-archer#229]
Archive出现了很多invalid date，咋解决

**Comment by shen-cheng-yu** [comment]
大佬解决问题了吗？我也有这个问题哎

**Comment by SenhuiWei** [comment]
我也有这问题

**Comment by Ifonly-go2019** [comment]
> 我也有这问题

在文章顶部,输入`---`,然后输入`date: 2020/02/11` 在重新commit就行咯~

**Comment by LolipopJ** [comment]
Archer 使用了 Hexo 提供的 [Front-matter](https://hexo.io/zh-cn/docs/front-matter.html)，请确保日期格式正确。

> Front-matter 是文件最上方以 `---` 分隔的区域，用于指定个别文件的变量
