### ISSUE TITLE
您好，帮您解决了一个侧边栏日期不显示年份的bug

### ISSUE THREAD

**Issue by NoCortY** [fi3ework/hexo-theme-archer#235]
在 source/scripts/main.js的第63行
修改为如下：
 dateFormater: function (t, e) {
                    var n = {
			"y+":t.getYear(),加上这句，获取年份
                        "M+": t.getMonth() + 1,
                        "d+": t.getDate(),
                        "h+": t.getHours(),
                        "m+": t.getMinutes(),
                        "s+": t.getSeconds(),
                        "q+": Math.floor((t.getMonth() + 3) / 3),
                        S: t.getMilliseconds()
                    };

**Comment by zhangguanzhang** [comment]
去提交一个pr吧

**Comment by removeif** [comment]
这边测试有显示，具体什么情况不显示？
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200304184718.png)

**Comment by NoCortY** [comment]
> 这边测试有显示，具体什么情况不显示？
> ![](https://camo.githubusercontent.com/b1bf1039b30f9249152b696c7b2b174042b95335/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f72656d6f766569662f626c6f675f696d6167652f696d672f323032302f32303230303330343138343731382e706e67)

时间过去挺长时间的了，有点记不住了，你可以试试看点分类或者标签弹出来的文章，是不是不显示年份
