### ISSUE TITLE
请问如何修改文章访问量数据。

### ISSUE THREAD

**Issue by XinAnzzZ** [fi3ework/hexo-theme-archer#236]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**

文章的访问量每次网页刷新都会加一，我希望修改代码，让同一个 ip 下多次刷新，只会加一次。

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**Comment by LolipopJ** [comment]
Archer 主题的文章访问量数据基于 [busuanzi](https://busuanzi.ibruce.info/)，作者提供的文档[在这里](https://ibruce.info/2015/04/04/busuanzi/#more)。

如果希望实现同 IP 只记录一次访问量的效果，可以更换为其它统计插件。

如果希望看到真实的访问情况统计，可以启用 Google 分析等第三方支持。

我将关闭此 Issue，如果您有更多的问题，欢迎重新打开！感谢理解！😄
