### ISSUE TITLE
可以使用宝塔面板吗

### ISSUE THREAD

**Issue by ranermay** [fi3ework/hexo-theme-archer#239]
**我使用宝塔面板然后不知道如何使用本主题**

**我把它放在wwwroot/我的ftp站点 目录下无法运行
**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by Stark-X** [comment]
Not related
