### ISSUE TITLE
按照所给方法无法改变代码块颜色

### ISSUE THREAD

**Issue by Eurus0209** [fi3ework/hexo-theme-archer#241]
按照所给的方法操作后，退回hexo总文件夹并执行命令 hexo g后，代码块颜色并未改变，求大佬帮助

**Comment by qingzistudio** [comment]
更改themes\archer\src\scss\_variables.scss里的$code-theme，有两处的$code-theme需要修改。你有可能没有改另一处。

**Comment by LolipopJ** [comment]
目前版本里仅需要修改一处了。

此 Issue 开启已久，我将关闭它 😘，如果有其它问题不妨重新打开！
