### ISSUE TITLE
为什么图片边框会出现一圈隐隐的阴影？

### ISSUE THREAD

**Issue by newstarwind** [fi3ework/hexo-theme-archer#242]
使用

{% img [class names] /path/to/image [width] [height] "title text 'alt text'" %}

插入图片后，为什么图片边框会出现一圈隐隐的阴影？这个效果能去掉吗？比较影响页面的整体效果。

多谢！

**Comment by newstarwind** [comment]
本地修改style.css后发现无用，因为发布后的页面会载入老css：
/css/style.css?v=20180824

这个在那里修改？

**Comment by lonuslan** [comment]
应该要重新npm build 主题目录

**Comment by LolipopJ** [comment]
现在可参考[此文档](https://github.com/fi3ework/hexo-theme-archer/blob/master/docs/develop-guide-zh.md#%E7%BC%96%E8%AF%91%E5%8F%91%E5%B8%83)，需要编译主题目录下的源文件，才能使对样式表文件的修改生效。
