### ISSUE TITLE
Algolia 全文检索

### ISSUE THREAD

**Issue by newstarwind** [fi3ework/hexo-theme-archer#243]
根据文档的方法添加Algolia搜索后，发现只能检索 文章标题，tag以及摘要内容，无法检索全文。

有办法支持全文检索吗？

多谢！

**Comment by Stark-X** [comment]
请尝试更新最新版，在当前版本无法复现，搜索正文关键字，可以返回包含关键字的文章

**Comment by LolipopJ** [comment]
目前提供的方法是通过为 Hexo 添加插件 [hexo-algolia](https://github.com/oncletom/hexo-algolia)，再执行 `./node_modules/.bin/hexo algolia` 命令实现读取博客 Markdown 文件，分析并上传索引。

而这个插件目前并**未支持**正文分词等高级特性。业界主流的方法是通过**网页爬虫**，自动读取网站并分析内容，进行智能分词最后将索引结果上传到 Algolia。

在这种情况下，您可以需要使用一些第三方爬虫服务（这意味着也许您需要为此功能付费），实现正文检索。

如果没有更多问题，我将关闭此 Issue，感谢您的理解！😄
