### ISSUE TITLE
通过更改样式主题文件夹内的css文件但是没有效果？

### ISSUE THREAD

**Issue by lonuslan** [fi3ework/hexo-theme-archer#245]
q:如题，因为在这个主题的主页，如果发布了文章，并且给这个文章加上了
`
- category: ***
- tag: ***
`
那么在主页下该文章的预览页右下角将会有这样的显示情况，**# your category or tag**，
除了文章预览页有这样的显示，还有点开文章之后，在文章的顶部，标题之后也会这样显示！
现在我要做的就是想删除category or tag前面的**#**。

于是我进入到样式文件夹，在\themes\archer\src\scss\_partial\_index-page.scss和\themes\archer\src\scss\_partial\_post-page.scss找到了其样式；
具体的在标签：**.post-tag**下的**::before**,于是我删除了**::before**的样式，但是似乎并不起作用，**#**符号还是存在。

so，不好意思，前端比较菜，请问有大佬知道如何解决这个问题吗？

**Comment by LolipopJ** [comment]
您做得很对，修改之后别忘了使用 `npm run build` 命令重新生成 CSS 文件。Hexo 博客将读取主题目录下 `source/css` 中的文件渲染博客。如果只是修改 SCSS 文件而没有生成 CSS 文件，那么修改将不会生效。

这个 Issue 已经打开快两年了，我将关闭此 Issue，假如您有更多的问题欢迎重新打开，感谢您的理解！😄
