### ISSUE TITLE
改主题颜色,重新build之后博客页面的文章就显示不出来了,为空白

### ISSUE THREAD

**Issue by awei-scut** [fi3ework/hexo-theme-archer#246]
problem:用npm build 之后hexo s,显示的页面为空白,除了顶部的图片,文字都显示不了
请问有人知道怎么解决么?build之后才出的问题

**Comment by lonuslan** [comment]
我想问为什么我每次只要build之后，再次hexo g编译就会报栈内存溢出的问题？而且build的时候，他的好多那个插件(我是这么理解的，对前端不是很熟)都过期了...

**Comment by IcecreamArtist** [comment]
对 好像build的时候很多插件都过期了，导致有些安装不上。。于是就无法更换主题色了

**Comment by LolipopJ** [comment]
现在版本的代码在我的机器上一切正常工作，使用的 Node.js 版本为 14.x。

如果没有进一步的问题，我将关闭此 Issue，感谢您的理解！😄
