### ISSUE TITLE
hexo g后public/avatar无法生成自己在本地/source/avatar/..设置的文件

### ISSUE THREAD

**Issue by 3cl1p53** [fi3ework/hexo-theme-archer#247]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**

首先表示，特别喜欢这个主题，很简洁漂亮～
在_config.yml文件中avatar: /avatar/me.jpg并且再目录下放置了图片文件
但是在hexo g后始终无法生成自己设置的文件，反而一直生成的是Misaka.jpg这个图片文件
请问是怎么回事呢

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: Mac OS[e.g. iOS]
 - 浏览器（Browser）: Chrome [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by LolipopJ** [comment]
So long...

呃，这个问题比较奇怪，请确保在 `archer/source/avatar` 目录下放置了 `me.jpg` 文件。

更好的方式是，在 **Hexo 博客的根目录**下的 `source` 目录创建一个新的文件夹，例如 `myAvatar`（什么都可以，只要避免命名冲突），然后在 `static` 目录下放置您的头像文件。最后在 Archer 主题配置的 `_config.yml` 中设置：`avatar: /myAvatar/me.jpg`

这样执行 `hexo g` 命令后，您的头像文件 `me.jpg` 会放置在生成的 `public/myAvatar` 目录下，并正确被 Archer 主题识别。

---

很抱歉现在才回复您。由于时间过久，我将关闭此 Issue，感谢您的理解！🥺
