### ISSUE TITLE
能否为主页的文章摘要添加格式？

### ISSUE THREAD

**Issue by vsxd** [fi3ework/hexo-theme-archer#248]
**提出你对主题的建议（Suggest your idea）**
能否为主页的文章摘要添加格式？
如果摘要没有格式，文章开头的部分又出现了代码，摘要会非常乱，失去了本身出现的意义。
而不显示摘要或者把摘要长度减太短又特别不协调。
我觉得摘要部分的格式正确显示是一个非常重要的功能。

**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**
文章默认的自提取摘要加入对标题、加粗、代码块等格式的支持，直接抛弃代码块都可以接受。

**提出其他的你考虑到的点（Describe alternatives you've considered）**

**其他**

**Comment by removeif** [comment]
> **提出你对主题的建议（Suggest your idea）**
> 能否为主页的文章摘要添加格式？
> 如果摘要没有格式，文章开头的部分又出现了代码，摘要会非常乱，失去了本身出现的意义。
> 而不显示摘要或者把摘要长度减太短又特别不协调。
> 我觉得摘要部分的格式正确显示是一个非常重要的功能。
> 
> **提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**
> 文章默认的自提取摘要加入对标题、加粗、代码块等格式的支持，直接抛弃代码块都可以接受。
> 
> **提出其他的你考虑到的点（Describe alternatives you've considered）**
> 
> **其他**

此功能太个性化了，建议自己个性化去写 class = abstract-content  样式，
文章开头的部分又出现了代码，摘要会非常乱 此情况完全可以由你控制，摘要本来描述文章大概，你写上代码似乎也不太合理，自己控制好 放好 more 标签在.md文件中合适位置就好了

**Comment by LolipopJ** [comment]
2021 年，尝试食用 [hexo-excerpt](https://github.com/chekun/hexo-excerpt) !
