### ISSUE TITLE
添加百度统计是不是在baidu_analytics后面跟上ID就可以直接使用了

### ISSUE THREAD

**Issue by Mr-Linus** [fi3ework/hexo-theme-archer#25]
还需不需要开其他东西，我站点在GitHub，把ID输入上去没有，那边检查没有安装代码

**Comment by Mr-Linus** [comment]
百度那边貌似没有看见ID，需要贴代码：
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?xxxx00000xxxxx";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

是不是要把xxxx0000xxx这个输入到ID里面

**Comment by fi3ework** [comment]
不需要的，你只要填写id就可以了，这是你主页里的脚本，显示已经插入了百度统计的代码，你自己也可以看下。
![image](https://user-images.githubusercontent.com/12322740/34154261-d4ab42ac-e4ef-11e7-9165-af254c70a746.png)
是不是百度统计那配错了，或者是有延迟什么的。

**Comment by Mr-Linus** [comment]
不知道额，检测了好几遍还是没有...

**Comment by Mr-Linus** [comment]
是不是要把那整个网址都填成ID

**Comment by fi3ework** [comment]
那就不知道，可能是百度的延迟吧，至少你页面的脚本里是正确的，和直接粘贴百度的代码效果是一样的。

**Comment by fi3ework** [comment]
我也是直接在_config里写的统计的id，百度统计是看得到的。

**Comment by Mr-Linus** [comment]
好的 我等会再试试 感谢！

**Comment by fi3ework** [comment]
😸

**Comment by secsilm** [comment]
@Mr-Linus 请问你解决了吗？我也遇到这样的情况了，前天还好的，昨天就不行了，百度统计也说检查不到代码，但是页面也是有的。

![](https://i.imgur.com/o6IZHrg.png)

**Comment by secsilm** [comment]
@Mr-Linus @fi3ework 貌似找到问题了，在`archer\layout\_partial\base-head.ejs`里的第 60 行原本为：

```javascript
hm.src = "<%- theme.baidu_analytics %>";
```

实际应为：

```javascript
hm.src = "https://hm.baidu.com/hm.js?<%= theme.baidu_analytics %>";
```

缺少了前面网址，导致最终只有一个 id，我改了之后就好了。

![](https://i.imgur.com/MvVCLO6.png)

**Comment by Mr-Linus** [comment]
好像应该把整个的网址贴上去

**Comment by secsilm** [comment]
@Mr-Linus 对，贴上去就好了，我已经提了一个 PR。

**Comment by fi3ework** [comment]
@secsilm 已merge，非常感谢发现这个bug~

**Comment by Mr-Linus** [comment]
😫你们好快啊，我刚想PR

**Comment by luhailiang98** [comment]
代码安装正确，页面上没有显示浏览量？

**Comment by fi3ework** [comment]
@luhailiang98 显示页面浏览量需开启不蒜子，默认为关闭，所以无法显示。已修改，不蒜子现在默认为开启，也可手动在_congfig.yml中将`busuanzi`改为`true`，感谢发现bug
