### ISSUE TITLE
再次上传文章会显示Invalid date

### ISSUE THREAD

**Issue by DGZ-cyber** [fi3ework/hexo-theme-archer#255]
最初文章以markdown格式导出到_posts文件夹，上传到博客，日期显示正常，后面对_posts文件夹中的文章(markdown格式)直接修改后，博客左边的栏该文章会显示Invalid date。

**Comment by removeif** [comment]
> 最初文章以markdown格式导出到_posts文件夹，上传到博客，日期显示正常，后面对_posts文件夹中的文章(markdown格式)直接修改后，博客左边的栏该文章会显示Invalid date。

你怎么修改的，修改了什么，目前测试，修改 .md文章中头部中的date 左栏archive是正常显示的修改后的date

**Comment by DGZ-cyber** [comment]
> > 最初文章以markdown格式导出到_posts文件夹，上传到博客，日期显示正常，后面对_posts文件夹中的文章(markdown格式)直接修改后，博客左边的栏该文章会显示Invalid date。
> 
> 你怎么修改的，修改了什么，目前测试，修改 .md文章中头部中的date 左栏archive是正常显示的修改后的date

好的谢谢，老老实实在.md文章中头部中加上date就ok了。
