### ISSUE TITLE
无法显示数学式子

### ISSUE THREAD

**Issue by zhou-ning** [fi3ework/hexo-theme-archer#266]
我使用了这个主题，但是好像无法正常渲染Latx的数学公式，请问有办法解决吗

**Comment by XudongX** [comment]
我写了篇文章，希望对你有帮助

[给Hexo主题添加LaTeX公式支持](https://adores.cc/posts/62947.html)

**Comment by MakerGYT** [comment]
@zhou-ning 试试[markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img#Hexo)

**Comment by LolipopJ** [comment]
Hexo 博客负责渲染 Markdown 文档，而与本主题无关。

其它部分主题可能内置了一些支持 JavaScript 库，但也仍需要在 Hexo 层面进行一定的配置。

可以参考这篇 [Wiki](https://github.com/fi3ework/hexo-theme-archer/wiki/%E5%90%AF%E7%94%A8-Latex-%E6%94%AF%E6%8C%81)。

如果没有更多问题，我将关闭此 Issue 😄
