### ISSUE TITLE
Fix Github's Security Alerts?

### ISSUE THREAD

**Issue by SketchK** [fi3ework/hexo-theme-archer#269]
**提出你对主题的建议（Suggest your idea）**
引用项目的主题时，Github 的 Security Alerts 会提示有些问题

**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**
升级一下对应的 npm 包，清理掉无用的依赖

**提出其他的你考虑到的点（Describe alternatives you've considered）**

**其他**

**Comment by LolipopJ** [comment]
最近我们更新了一下依赖库的版本（#285），感谢您的提醒与支持！😘

---

如果没有更多问题，我将关闭此 Issue，谢谢理解！😃
