### ISSUE TITLE
如何添加备案信息

### ISSUE THREAD

**Issue by GoldenRockSpace** [fi3ework/hexo-theme-archer#271]
国内的域名要求在底部添加备案信息，请问该如何操作

**Comment by removeif** [comment]
![image](https://user-images.githubusercontent.com/10427139/82656149-de108800-9c55-11ea-9283-b4dc37f60cef.png)
footer里加一行
```html
<span><br>© <a href="http://www.beian.miit.gov.cn/" target="_blank">豫ICP备20003023号</a><br></span>
```

**Comment by LolipopJ** [comment]
顺带一提，Footer 代码可以在 `layout/_partial/base-footer.ejs` 中编写。

---

如果没有更多问题，我将关闭此 Issue，感谢理解！😊

**Comment by GoldenRockSpace** [comment]
万分感谢

JasonSun ***@***.***> 于2021年5月23日周日 上午2:11写道：

**Comment by LolipopJ** [comment]
现在您可以尝试拉取此仓库的最新代码，通过配置 `website_approve` 来添加备案信息了！😉
