### ISSUE TITLE
特效

### ISSUE THREAD

**Issue by Cgy-codelab** [fi3ework/hexo-theme-archer#279]
想问如果自己加特效，应该写在哪个地方

**Comment by LolipopJ** [comment]
您可以在 Archer 主题下的 `src` 目录下编写 .js 和 .scss 代码，在 `layout` 目录下编写 .ejs 代码。发挥您的创造力！👨‍💻

阅读[二次开发文档](https://github.com/fi3ework/hexo-theme-archer/blob/master/docs/develop-guide-zh.md)以了解开发前的准备和步骤。

---

我将关闭此 Issue。感谢理解！😊
