### ISSUE TITLE
demo网页出错

### ISSUE THREAD

**Issue by lsq210** [fi3ework/hexo-theme-archer#281]
在线预览demo网页好像出了点问题

**Comment by secsilm** [comment]
好像确实出问题了，可能域名到期了？可以参考 [我的博客](https://alanlee.fun/)，就是用的这个主题，只不过修改了字体。

**Comment by LolipopJ** [comment]
@fi3ework Hi，有空的话，可以修复一下国内的在线预览 Demo 的镜像链接。🙏

我暂时先使用 [github.io 链接](https://fi3ework.github.io/archer-demo/)代替了。

**Comment by Stark-X** [comment]
closed by #322
