### ISSUE TITLE
busuanzi统计失效

### ISSUE THREAD

**Issue by Asinta** [fi3ework/hexo-theme-archer#282]
**busuanzi的统计console显示获取访问量返回400**

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [ x ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [ x ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**https://ashy-stone-0d95aee00.azurestaticapps.net/**

![image](https://user-images.githubusercontent.com/52993526/98765009-0b294080-2418-11eb-8a6e-9a72a9cfd194.png)

**信息 (please complete the following information):**
 - 操作系统（OS）: macOS
 - 浏览器（Browser）chrome

** Hosted on Azure Static Website **

**Comment by BestBonBai** [comment]
我在手机端查看可以正常显示busuanzi的统计，但是PC网页端不显示，这是怎么回事啊？

**Comment by LolipopJ** [comment]
@Asinta 在我这里使用电脑端和手机端都能正常显示[您博客](https://ashy-stone-0d95aee00.azurestaticapps.net/)上的 busuanzi 统计结果。

Archer 主题参照[不蒜子](https://busuanzi.ibruce.info/)提供的方式引入 JavaScript 库：

```ejs
<!-- layout/layout.ejs -->
<% if (theme.busuanzi) { %>
    <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
<% } %>
```

由于使用的是不蒜子提供者的服务器（感恩），因此有可能出现第三方网络故障，导致没能顺利下载 busuanzi 库的情况；此外也可能是电脑代理设置的问题。与 Archer 主题本身无关。

如果没有更多问题，我将关闭此 Issue，感谢理解！😄
