### ISSUE TITLE
在文章页，点击左上角，会出现一大片空白

### ISSUE THREAD

**Issue by nalani5210** [fi3ework/hexo-theme-archer#283]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [√ ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [√ ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

![image](https://user-images.githubusercontent.com/75011832/101463588-9561b780-3978-11eb-89ee-02e618279049.png)

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by LolipopJ** [comment]
看上去文章页的侧边栏没有正确渲染到页面左侧并隐藏，而是直接显示到了头图下方的左侧。

考虑到侧边栏使用的 CSS 代码使用到了 Flex 布局，对**较老**浏览器兼容性较差，也许您可以提供一下您浏览器的版本，帮助进一步排查问题！
