### ISSUE TITLE
请问有考虑把”文章置顶“放到配置文档吗

### ISSUE THREAD

**Issue by ElegantNorlin** [fi3ework/hexo-theme-archer#289]
**提出你对主题的建议（Suggest your idea）**

**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**

**提出其他的你考虑到的点（Describe alternatives you've considered）**

**其他**

**Comment by LolipopJ** [comment]
呃，并不是很能读懂您的问题，或许您可以更详细描述一下您想要做的事情！✍️

**Comment by ElegantAlan** [comment]
> 呃，并不是很能读懂您的问题，或许您可以更详细描述一下您想要做的事情！✍️

不好意思，我打错字了，请问文章置顶功能可以放到配置文档直接设置好吗

**Comment by LolipopJ** [comment]
目前的置顶功能是通过在 _post 中文章的 Front-matter 部分添加 `sticky: 优先级数字` 实现。这个功能基于 Hexo 依赖 [hexo-generator-index](https://github.com/hexojs/hexo-generator-index)。

---

如果在 Hexo 根目录或 Archer 根目录的 `_config.yml` 文件中配置置顶文章，似乎价值不大。😲 例如您需要取消置顶一篇文章，只需要删除对应博文的 `sticky` 属性或降低优先级就可以了。
