### ISSUE TITLE
「反馈 Bug」TOC 目录无法显示过长内容

### ISSUE THREAD

**Issue by Varonne** [fi3ework/hexo-theme-archer#296]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**

当同一级标题过多时，右侧 TOC 目录因为没有滚动条所以超出部分无法显示，效果如下

[![图1](https://z3.ax1x.com/2021/05/23/gXQPPg.png)](https://imgtu.com/i/gXQPPg)
[![图2](https://z3.ax1x.com/2021/05/23/gXQ9IS.png)](https://imgtu.com/i/gXQ9IS)

不知道能不能添加滚动条或者让 toc 目录自动滚动，类似 [这个主题](https://butterfly.js.org/posts/4aa8abbe/#inlineImg) 效果

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**信息 (please complete the following information):**
 - 操作系统（OS）: [Windows 10]
 - 浏览器（Browser） [Cent Browser]
 - 浏览器版本（Version）[Chromium 86.0.4240.198]

**Comment by LolipopJ** [comment]
这确实是一个问题！😲

应该可以通过给旁边的 TOC 目录添加 style，设置 `overflow: scroll;` 和高度修复。

感谢您的反馈，我将把这个问题放到 TODO 中！😉

修复后（考虑到暂无活跃的维护者，不知道多久之后……）会通知您！您也可以帮助我们 Fix 这个 Bug，并提交合并请求。🥺

**Comment by Varonne** [comment]
感谢您的帮助！

可惜本人能力有限，暂时没想到好的显示方案，所以可能帮不上什么忙。😔

**Comment by LolipopJ** [comment]
现在最新版本的主题，当鼠标在 Catalog 内，可以滑动 TOC 目录了 😉

我将关闭这个 Issue，如果引发了其它的问题，欢迎重新打开这个 Issue ━(*｀∀´*)ノ亻
