### ISSUE TITLE
考虑使用[probot/stale](https://github.com/probot/stale) 把过时的 issue 关掉？

### ISSUE THREAD

**Issue by Stark-X** [fi3ework/hexo-theme-archer#297]

**Comment by LolipopJ** [comment]
最近查看了很多遗留下来的 Issue，大多数已经随着代码更迭而已经解决，少部分 Issue 可以手动回答并关闭。

目前 Issue 量级并不大，可能不需要 probot/stale，便可以一个一个手动检查并关闭。

有空的时候我来负责这块吧。
