### ISSUE TITLE
更改主题颜色问题

### ISSUE THREAD

**Issue by sqmwin** [fi3ework/hexo-theme-archer#30]
在archer目录下执行`gulp build`命令,返回无此命令,是什么情况

**Comment by fi3ework** [comment]
执行`npm install`了吗

**Comment by sqmwin** [comment]
执行了,按着步骤来的

**Comment by fi3ework** [comment]
请问是windows平台下马

**Comment by sqmwin** [comment]
是的

**Comment by fi3ework** [comment]
这个可能是npm安装的问题，可以参照一个[这个](https://stackoverflow.com/questions/24027551/gulp-command-not-found-error-after-installing-gulp)

**Comment by sqmwin** [comment]
好的谢谢 我试试
