### ISSUE TITLE
主题可以新增自定义 menu 的 feature 吗

### ISSUE THREAD

**Issue by OreChou** [fi3ework/hexo-theme-archer#308]

**Comment by LolipopJ** [comment]
可以具体描述一下 Menu 指哪方面吗。

是说打开侧边栏菜单的**按钮**，还是顶部**导航栏**之类的呢？

**Comment by OreChou** [comment]
> 可以具体描述一下 Menu 指哪方面吗。
> 
> 是说打开侧边栏菜单的**按钮**，还是顶部**导航栏**之类的呢？

主页头像下面的 menu 入口。例如 Friends、About Me，下面可以自定义新的页面入口。

**Comment by LolipopJ** [comment]
好主意！

未来 Archer 主题如果适配了更多的独立页面，可以将页面入口添加到这里。

现在，作为可选的配置添加到 `_config.yml` 里边我想应该不难适配。我将把这个需求放到 TODO 中去，有缘适配。

---

目前，您可以参考 [`layout\_partial\base-profile.ejs`](https://github.com/fi3ework/hexo-theme-archer/blob/master/layout/_partial/base-profile.ejs) 中已有的内容，自行添加菜单项：

``` ejs
<div class="about-me">
  <a href="<%- url_for("/about") %>">ABOUT ME</a>
</div>
```

对 .ejs 文件的修改无需执行 `npm run build` 操作。

**Comment by OreChou** [comment]
好的！多谢你的帮助，祝愿 Archer 越来越好

**Comment by LolipopJ** [comment]
New feature added here.
