### ISSUE TITLE
[CSS]article 元素增加  overflow:hidden 或overflow: auto

### ISSUE THREAD

**Issue by ted423** [fi3ework/hexo-theme-archer#309]
**提出你对主题的建议（Suggest your idea）**
默认似乎是visible?这种情况下，在文章里添加一些奇怪的元素（例如float）很可能会超出范围影响到整体页面布局
**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**

**提出其他的你考虑到的点（Describe alternatives you've considered）**

**其他**

**Comment by LolipopJ** [comment]
来点代码康康。

如果可以的话，上个图就更直观了！

**Comment by ted423** [comment]
> 来点代码康康。
> 
> 如果可以的话，上个图就更直观了！

https://ted423.github.io/Anime/Zootopia/
这是加了后的

**Comment by LolipopJ** [comment]
感谢反馈！

已将代码添加到 dev 1.6.4 分支中，等待合入主分支。

**Comment by LolipopJ** [comment]
注意到自行添加的浮动元素在手机端的显示并不好，我认为可以单独创建一个样式表，例如命名为 `float-right-element`。在编写 md 文档时直接设置这个样式表类。

在 Desktop（960 px 以上）时，显示为靠右浮动；在 Mobile 时，显示为 static 定位元素。

**Comment by ted423** [comment]
这个转的以前的博客，css直接抄的wiki的。当时是半桶水，现在也是。
目前其实还在搬博客中

**Comment by LolipopJ** [comment]
Getting done [here](https://github.com/fi3ework/hexo-theme-archer/tree/dev-1.6.4#%E6%B5%AE%E5%8A%A8%E5%85%83%E7%B4%A0).
