### ISSUE TITLE
「CD」添加 Demo 网页持续集成

### ISSUE THREAD

**Issue by LolipopJ** [fi3ework/hexo-theme-archer#312]
目前预览网页失联已久，且较新的代码并没有体现在 Demo 网页上。

考虑单独开 `gh-source` 分支，搭建完整的 Hexo 项目和示例博客文件，在 `themes/archer` 目录下拉取 `master` 分支代码。当 `gh-source` 分支代码更新时，触发 Github Actions，构建 Hexo 博客静态文件，并将静态文件推送到 `gh-pages` 分支，供 Github pages 读取并展示。

**Comment by Stark-X** [comment]
这个应该叫 CD，不是 CI，这个我可以整

**Comment by Stark-X** [comment]
根据[官方文档](https://docs.github.com/cn/pages/getting-started-with-github-pages/creating-a-github-pages-site)，GitHub Page 必须要由 owner 创建，且仓库名称必须为 `<user>.github.io` 或 `<organization>.github.io`

**Comment by LolipopJ** [comment]
可以联系 @fi3ework 帮忙将对应分支开成 github pages，这样可以通过 `fi3ework.github.io/hexo-theme-archer` 这个链接访问了

**Comment by fi3ework** [comment]
@LolipopJ @Stark-X 可以新建一个做 preview 的分支，然后我开成 github pages
