### ISSUE TITLE
我想询问一下如何分享文章。

### ISSUE THREAD

**Issue by BeeeeeeLazy** [fi3ework/hexo-theme-archer#313]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
我想使用文章分享的功能，但是鼠标移动到相对应的图标后，点击没有反应。
所以想询问一下，如何启用这个分享的功能。
我看demo中是有分享的。

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [ x ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [ x ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
http://106.15.53.70/2021/09/06/433M%E9%81%A5%E6%8E%A7%E5%99%A8%E6%8E%A5%E6%94%B6/#/%E7%A1%AC%E4%BB%B6%E5%8E%9F%E7%90%86%E8%AF%B4%E6%98%8E

**Comment by LolipopJ** [comment]
Holy **，某次我提交时修改了 `layout\_partial\base-background-image.ejs` 中分享列表的类名，从 `shareList` 修改为更规范的 `share-list`。然而我并没有修改 `src\js\share.js` 中查询此元素的代码，意味着它搜索了一个不存在的元素，也因此导致了这个问题的出现。

我将立即修复这个问题并推送到主分支，感谢您的指出！

**Comment by LolipopJ** [comment]
我将关闭此 Issue，如果它仍不工作，请打开此 Issue 让我知道。😀
