### ISSUE TITLE
[Dev]更了下dev,然后发现toc-wrapper没了，就是右侧那个根据本章内小标题生成的列表

### ISSUE THREAD

**Issue by ted423** [fi3ework/hexo-theme-archer#317]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
https://github.com/fi3ework/hexo-theme-archer/issues/316
因为这个issue升的
确认了下 toc确实是enable的
**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by ted423** [comment]
感觉是跟这个报错有关
![image](https://user-images.githubusercontent.com/7042766/135131637-866aed5c-ed8c-45c8-a673-15d63531b80a.png)
因为显示的两个数据只是二级标题

**Comment by LolipopJ** [comment]
我这边使用 dev 分支代码并没有出现渲染失败的问题……

或许尝试一下 Hexo 根目录执行 `hexo clean` 清除以前版本的缓存文件避免冲突？

**Comment by ted423** [comment]
> 我这边使用 dev 分支代码并没有出现渲染失败的问题……
> 
> 或许尝试一下 Hexo 根目录执行 `hexo clean` 清除以前版本的缓存文件避免冲突？

我这边尝试了hexo clean
也试了删除主题文件，重新解压也是一样

**Comment by ted423** [comment]
我重新弄了一下，现在没报错了，只是单纯不显示，有个opacity: 0;
不知道为什么

**Comment by ted423** [comment]
又试了下，现在没有报错，主要是
  &-loding {
    opacity: 0;
  }
这个的问题

**Comment by LolipopJ** [comment]
`src/js/toc.js` 执行的最后一步移除了其未就绪的等待状态：`$('.toc-wrapper').removeClass('toc-wrapper-loding')`。我这边能够正常移除：

![image](https://user-images.githubusercontent.com/42314340/135376649-0b25c9a4-27e2-4284-876d-d3a389a871ec.png)

也许还是您那边的脚本文件未能正确执行？是每一篇博客都出现了这个问题吗？

**Comment by ted423** [comment]
我发现又开始报错了，每篇都有。报错是导致右边的二级标题无法展开

toc.js:142 Uncaught TypeError: Cannot set property 'onclick' of undefined
    at i (toc.js:142)
    at s (toc.js:125)
    at L (toc.js:194)
    at HTMLDocument.<anonymous> (init.js:45)

**Comment by ted423** [comment]
https://ted423.github.io/Anime/Frozen/#/P2P
似乎是因为i超了上限，i是14，但二级标题只有11个

**Comment by ted423** [comment]
只有1级标题的情况下，archorjsLinks length是0,但是仍然会读下，导致报错，我现在是吧loding 那个opacity注释掉了
https://ted423.github.io/Software/tools/#KeePassXC

**Comment by LolipopJ** [comment]
我想问题出在每个标题后的这个小链接图标：

![image](https://user-images.githubusercontent.com/42314340/135378216-23f5545a-19af-40c9-a2f7-e0a7be671b23.png)

它并没有在执行脚本前渲染出来，我想应该修改一下渲染顺序试试看。

我再加一个判断，如果不存在这个 `archorjsLinks`，就跳过：

``` js
if (archorjsLinks.length && archorjsLinks.length > i) {
  archorjsLinks[i].onclick = () => {
    tocOnclickFunction()
    return false
  }
}
```

**Comment by LolipopJ** [comment]
目前 toc.js 存在一些问题，我计划后面将它重写一遍。

**Comment by ted423** [comment]
了解，不急哈

**Comment by LolipopJ** [comment]
Fixed [here](https://github.com/fi3ework/hexo-theme-archer/releases/tag/1.6.6).
