### ISSUE TITLE
想要限制「文章目录」仅支持到某个目录级别

### ISSUE THREAD

**Issue by zhullyb** [fi3ework/hexo-theme-archer#318]
**提出你对主题的建议（Suggest your idea）**

建议增加对于「文章目录」的标题级数限制: 比如支持在配置文件中设置只有2~4级标题才能显示

我有一篇文章使用了3个二级标题、11个三级标题、22个司机标题以及84个五级标题，他们全部都显示在「文章目录」中，导致「文章目录」在屏幕上无法完整显示出来。
![图片](https://user-images.githubusercontent.com/43305366/135828395-5b9ce907-f12f-40f5-a9ae-4e53cd161a5f.png)

**Comment by LolipopJ** [comment]
在较新版本的主题中 https://github.com/fi3ework/hexo-theme-archer/issues/296#issuecomment-868702931 ，已经支持 toc 的滑动了

**Comment by zhullyb** [comment]
好，那我把这个issue关了

________________________________
发件人: JasonSun ***@***.***>
发送时间: 2021年10月4日星期一 下午5:47
收件人: fi3ework/hexo-theme-archer
抄送: zhullyb; Author
主题: Re: [fi3ework/hexo-theme-archer] 想要限制「文章目录」仅支持到某个目录级别 (#318)


在较新版本的主题中 #296 (comment)<https://github.com/fi3ework/hexo-theme-archer/issues/296#issuecomment-868702931> ，已经支持 toc 的滑动了

―
