### ISSUE TITLE
jsDelivr 相关问题

### ISSUE THREAD

**Issue by LolipopJ** [fi3ework/hexo-theme-archer#328]
主题内用到的第三方库大多数使用了 jsDelivr 作为 CDN 进行加速，但据目前[官方的说法](https://twitter.com/jsDelivr/status/1472870623051456522)，由于国内 ICP 备案问题，境内的服务器节点暂时无法使用，而是将流量转移到就近的其它服务器节点上。

考虑到主题的用户和访问者有相当一部分系中国人，该问题尚不可知会对访问速度等造成何等的影响，如果境内的服务器节点故障无法得到修复，可能需要切换至其它的 CDN 服务运营商。

**Comment by Stark-X** [comment]
现在国内的流量被路由到靠近中国大陆的周边节点，访问恢复了。参考“站长工具”的 全球 ping 工具的[结果](https://ping.chinaz.com/cdn.jsdelivr.net)，速度会有较为明显的影响，替换成 [upkg.com](https://ping.chinaz.com/upkg.com) 也是类似的。
不过，在用户第一次加载后，浏览器使用本地缓存，速度影响估计不会太大，目前也没有更好的解决办法。
