### ISSUE TITLE
请问为何&emsp;&ensp;等不起作用，是直接显示出来的?

### ISSUE THREAD

**Issue by CyanStudio** [fi3ework/hexo-theme-archer#336]

**Comment by LolipopJ** [comment]
写在博客文档的 Markdown 文件里的吗？解析器在处理  Markdown 文本时不会像浏览器一样转义 &ensp; 这类字符，而是直接作为字符串显示出来。考虑使用 html 标签如 `<div style="margin-left: 5px" />` 来实现空格效果。

**Comment by CyanStudio** [comment]
是写在_post下Markdown文件里的，不过确实不起作用，只能用html标签试试了。
