### ISSUE TITLE
不太理解的外部脚本请求

### ISSUE THREAD

**Issue by ted423** [fi3ework/hexo-theme-archer#338]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
busuanzi.pure.mini.js:1 
  GET https://busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback_830052199995 net::ERR_ABORTED 502
这个commit中被引用
https://github.com/fi3ework/hexo-theme-archer/commit/5ae8a3d357860d30f94bd277df886fc082736e53

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by LolipopJ** [comment]
buduanzi pv 统计：

https://busuanzi.ibruce.info/

**Comment by ted423** [comment]
> buduanzi pv 统计：
> 
> https://busuanzi.ibruce.info/

刚查到了

**Comment by ted423** [comment]
我以为脚本连接挂了，看起来是偶然的bad gateway
