### ISSUE TITLE
文章目录的编号可以自己设置开关吗？

### ISSUE THREAD

**Issue by TracyWang-0** [fi3ework/hexo-theme-archer#339]
在写博客的时候，自己一般是会为大标题添加序号的
然而在浏览该博客页面的时候，可以看到每个标题左边又自动添加了序号，如下图，这样看起来让我感觉有点别扭
<img width="189" alt="image" src="https://user-images.githubusercontent.com/68034401/167669550-e9e8b1d0-ec2f-496d-9426-9f768b4f81ef.png">
但是我没有学过前端，不知道如何修改，希望可以得到帮助！
万分感谢！！

**Comment by LolipopJ** [comment]
可以手动修改主题的布局文件 `layout/layout.ejs` 中的配置：

https://github.com/fi3ework/hexo-theme-archer/blob/de5d47345433ae32eacd9ee66042579cf3c0f7e4/layout/layout.ejs#L44

将 `list_number: true` 改成 `list_number: false` 就行了（大概）。

**Comment by TracyWang-0** [comment]
非常感谢您的回复！！
刚才通过邮件中提供的方法尝试后，已经修改成功啦~


祝平安喜乐！


| |
王越越
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年05月11日 ***@***.***> 写道：

可以手动修改主题的布局文件 layout/layout.ejs 中的配置：

https://github.com/fi3ework/hexo-theme-archer/blob/de5d47345433ae32eacd9ee66042579cf3c0f7e4/layout/layout.ejs#L44

将 list_number: true 改成 list_number: false 就行了（大概）。
