### ISSUE TITLE
sticky排序在sidebar和文章内的排序

### ISSUE THREAD

**Issue by LuLu010722** [fi3ework/hexo-theme-archer#348]
**提出你对主题的建议（Suggest your idea）**
目前的sticky排序，仅仅在index页面有效，在侧边栏和文章内的prev，post顺序，仍然是默认顺序，这造成了一定的不一致性。
**提出你觉得可行的解决方案 [可选]（Describe the solution you'd like）**
可否将sticky排序也应用于以上两个地方
**提出其他的你考虑到的点（Describe alternatives you've considered）**

**其他**

**Comment by LolipopJ** [comment]
侧边栏主要目的为按时间归档博客；sticky 原则只实现物理置顶，不实现逻辑置顶，所以 Prev 和 Next 排序不发生改变。

考虑可以修改博客的布局代码（[在这里](https://github.com/fi3ework/hexo-theme-archer/blob/master/layout/post.ejs#L15-L33)），配置根据博客的 Front-matter 是否设置 `paginator: false` 来指定某篇博客是否显示页脚。

**Comment by LuLu010722** [comment]
好吧~
谢谢回复
