### ISSUE TITLE
markdown table 功能

### ISSUE THREAD

**Issue by Changzw** [fi3ework/hexo-theme-archer#35]
不支持 markdown 的table 功能吗？

| 1       | 2     | 3     |
| :-----------: | :----------: | :----------: |
| aaa        | bbb | ccc   |

**Comment by fi3ework** [comment]
肯定是支持啊，http://firework.studio/archer-demo/2013-12-24/elements/
![image](https://user-images.githubusercontent.com/12322740/35195453-8ed0c9ea-fefe-11e7-99d8-529aeb270944.png)
暂时不知道你是怎么写的，我猜可能是github的markdown解析器和hexo的不一致，所以你把相同写法放到github上可以，hexo就不行。所以最好按照标准写法来写，hexo才能解析😀

**Comment by Changzw** [comment]
…… 这么快的吗？给你疯狂打call
我没有在链接后 换行，在本地 markdown 编辑不会有问题，可是浏览器要table 上面换行

**Comment by fi3ework** [comment]
是的，不同markdown编辑器用的是不同的解析器，hexo的这个怎么说，要求比较严格，标准写法好像就是要换行的。（就在电脑前就回了）

**Comment by Mr-Linus** [comment]
我clone的最新的archer,但是表格显示有问题,看了下网页代码的确渲染成了table  @fi3ework ,可以帮我看下吗
 <http://localhost:4000/2018/07/17/test/>
