### ISSUE TITLE
表格的表头渲染到文章顶部，显示异常

### ISSUE THREAD

**Issue by LuLu010722** [fi3ework/hexo-theme-archer#351]
我启用了一个pandoc的渲染器
此时我发现，在本地typora编写表格，在hexo上显示的大概是这样：

![image](https://user-images.githubusercontent.com/62323571/195994634-00de3b48-6701-4713-b770-87818121bcb2.png)

尝试按照archer的推荐配置pandoc并且编写表格可以复现该问题。
原博客网址：https://lulu010722.cn/2022/10/15/%E6%B5%8B%E8%AF%95/

md原文：

\# 表格测试

\| 1   \| 2    \| 3    \|
\| ---- \| ---- \| ---- \|
\| 甲   \| 乙   \| 丙   \|

**Comment by LolipopJ** [comment]
![image](https://user-images.githubusercontent.com/42314340/196001986-bbc7c4b0-f659-4b85-a7c4-5e7ce1b766db.png)

排查出来问题的原因在于表格的表头使用到了重复的 `header` 样式类，而这个样式类原计划仅使用于博客的顶部 Header。这个问题源于未能使用样式隔离，我会通过修改表格表头的样式类名来修复这个问题。
