### ISSUE TITLE
TOC malfunction

### ISSUE THREAD

**Issue by lulu010722** [fi3ework/hexo-theme-archer#357]
The toc on the right side of the post main content, is not working correctly.

First, the link's position is not correctly located.
Second, click on the link inside the post content does not give reasonable redirection.
Third, when scrolling up and down, the automatic updating of toc is not correct.

Feel free to try on these 2 pages.
https://lulu010722.cn/2022/10/15/%E6%B5%8B%E8%AF%95/
https://lulu010722.cn/2022/10/15/ICS%E5%A4%8D%E4%B9%A0/

Sorry for posting too many issues and prs these days...
But this is beyond my ability.
I am not sure how to modify the src.

Please have a look at the problem.

**Comment by LolipopJ** [comment]
Toc 确实存在很多已知的问题，我计划后续重写一下 Toc 相关的源码，后面有空的时候我做一下吧 🐵。

https://github.com/fi3ework/hexo-theme-archer/issues/317#issuecomment-930747946

**Comment by LolipopJ** [comment]
> Toc 确实存在很多已知的问题，我计划后续重写一下 Toc 相关的源码，后面有空的时候我做一下吧 🐵。
> 
> [#317 (comment)](https://github.com/fi3ework/hexo-theme-archer/issues/317#issuecomment-930747946)

突然发现我这都摸了一年多了…… 😅

**Comment by LuLu010722** [comment]
你对得起我们吗？退钱！（bushi哈哈哈
我也可以尝试写一下，如果写完了我交个pr吧。
不过可能会触发更多bug就是了...

**Comment by LolipopJ** [comment]
Fixed [here](https://github.com/fi3ework/hexo-theme-archer/releases/tag/1.6.6).

If more trouble is caused, feel free to re-open this issue. XD
