### ISSUE TITLE
URL不随浏览页面变动

### ISSUE THREAD

**Issue by Yao-Lirong** [fi3ework/hexo-theme-archer#369]
**提出你对主题的建议（Suggest your idea）**

当前行为是进入一个博文页面后自动向url添加 `#/` ，并随着用户下滑，URL也会发生变化。这样做会导致使用浏览器自带的后退无法回到上一页面。可否 默认/添加选项 使得仅当点选目录的时候url才会发生变化？

比如在[这个页面](https://yao-lirong.github.io/2022-12-31-2022-%E7%BD%91%E7%BB%9C%E6%97%A5%E5%BF%97/)试着稍微用滚轮下滑一会再点浏览器自带的返回，会发现非常麻烦。

**其他**

据我所知大部分网站的url都是不会随着浏览而改动的，对网页开发所知甚少，希望您考虑。

**Comment by LolipopJ** [comment]
看上去修改 URL 的时候生成了新的 history 记录，这本来是应当避免的情况。🧐 我会尝试修复这个问题，感谢反馈！

**Comment by LolipopJ** [comment]
Fixed [here](https://github.com/fi3ework/hexo-theme-archer/releases/tag/1.6.6).

If more trouble is caused, feel free to re-open this issue. XD
