### ISSUE TITLE
我想设置我自己的字体

### ISSUE THREAD

**Issue by lulu010722** [fi3ework/hexo-theme-archer#376]
前几天在网上下载了一套很好看的本地字体，请问怎么加进去呢？

**Comment by LuLu010722** [comment]
![image](https://github.com/fi3ework/hexo-theme-archer/assets/62323571/9dfd0112-f85b-4065-a926-4d0d931f3ba7)
这是我进行的设置

**Comment by LolipopJ** [comment]
没有自己测试跑过，提供经验可用以参考：

- **本机提供字体包**：字体文件不会交由 SCSS 打包，因此相对路径没有效果。应当采用绝对路径的形式，对于 `/source/font` 下的文件，会存放在网站资源的 `/font` 目录下（见下图）。因此，在编写 SCSS 文件时，资源链接应使用绝对路径的 `src: url('/font/font-file.otf')`。原作者在引入自定义字体文件时，直接在 EJS 文件中引入，也是可行的（可[见此](https://github.com/fi3ework/hexo-theme-archer/blob/0a012d5d12e7a9680503329c133f75bddc07d8df/layout/_partial/critical-css/critical-style.ejs#L4)）。

![字体文件路径](https://github.com/fi3ework/hexo-theme-archer/assets/42314340/d1771a8f-687b-4e8f-b3d0-530b0abf6ee1)

- **CDN 加载字体包**：中文字体文件通常较大，其他人访问时通常会等待 *非常久*，如果一定要加上自己喜欢的中文字体，建议将字体文件托管到 CDN 上进行加载，避免用户因等待而失去耐心，进而关闭网页！

从博客的角度来说，一般**不建议**添加自定义的中文字体（导致初次访问等待时间长），访客的耐心十分宝贵，用户的体验应该放于首位。使用用户首选的系统字体，或使用用户系统通常包含的字体是更好的方案。

**Comment by lulu010722** [comment]
好的谢谢，不过我发现我的字体好像是win自带的，所以就直接写了
