### ISSUE TITLE
github action不自动执行了

### ISSUE THREAD

**Issue by lulu010722** [fi3ework/hexo-theme-archer#379]
你加了workflow里面的那三个文件之后，好像现在hexo d完了之后，仓库不会自动github action了

**Comment by LolipopJ** [comment]
对 `.github/ISSUE_TEMPLATE` 进行了格式化，应该不会影响到 `.github/workflow` 里的工作流文件。但是对依赖包版本做了升级，建议修改工作流中使用的 node 版本为 16.x。

**Comment by lulu010722** [comment]
啊对，我nvm换了node版本之后好像就好了。
好像又没问题了。
就是之前hexo deploy之后，在远端的仓库上都会自动执行github action的脚本嘛，然后前两天我部署了几次有几次没有自动执行那个脚本，一般都是自动执行的。
