### ISSUE TITLE
"返回顶部"标签透明度问题

### ISSUE THREAD

**Issue by frozentea** [fi3ework/hexo-theme-archer#38]
您好，我使用的是上一版（2/4之前）的模板，当我试图通过修改 _common.scss 文件，使“返回顶部”的标签也显示为半透明时，把
`background-color: white;`
修改为
`background-color: rgba(255, 255, 255, 0.7);`
然而最终是无效的。
请问正确的修改姿势是怎样的？
thanks

**Comment by fi3ework** [comment]
请问改完之后执行`gulp build`了吗

**Comment by frozentea** [comment]
执行了

**Comment by fi3ework** [comment]
我明天看下吧，现在不在电脑前😂

**Comment by frozentea** [comment]
嗯嗯多谢，挺晚的了。你的主题很棒 (￣▽￣)～■干杯

**Comment by fi3ework** [comment]
应该改`.back-top-show`的`background-color`，之前的代码写的比较乱，尤其是CSS这块 :joy:

**Comment by frozentea** [comment]
实测有效，已解决 :ok_hand:。谢谢
