### ISSUE TITLE
如何修改中文？

### ISSUE THREAD

**Issue by hyy34** [fi3ework/hexo-theme-archer#381]
修改_config.yml language: zh-CN但是好多还是英文？例如左上角的标签页，文章的Next Post Previous Post还有上方的share，如何彻底修改成中文呢？

**Comment by Stark-X** [comment]
你可以参考 https://github.com/fi3ework/hexo-theme-archer/blob/4559f799b020a14a9c7a08066536243b3d337414/layout/post.ejs#L10
同时，修改 languages/default.yml 以及 languages/en.yml 添加相对应的中英文，即可。

**Comment by hyy34** [comment]
修改了，主题文件夹里的各种ejs文件，应该都改过来了。。

但是有个问题，如果配置文件里(copyright:)改为true了，那么日期如何变为中文显示？

**Comment by Stark-X** [comment]
`Invalid date` 跟配置中英文没关系，是解析的日期不规范导致的，例如如果日期为`none`等情况

`Catalog` 在这里
https://github.com/fi3ework/hexo-theme-archer/blob/4559f799b020a14a9c7a08066536243b3d337414/layout/layout.ejs#L42

可以参考我之前的回复的位置，添加翻译模板，再重新构建就可以了。

> 你可以参考
> 
> https://github.com/fi3ework/hexo-theme-archer/blob/4559f799b020a14a9c7a08066536243b3d337414/layout/post.ejs#L10
> 
> 
> 同时，修改 languages/default.yml 以及 languages/en.yml 添加相对应的中英文，即可。

**Comment by hyy34** [comment]
> hexo-theme-archer/layout/post.ejs

post.ejs的文件还是没有看懂。

Invalid date 必须要在文章头部 加上 [data：](date: '2023-09-06 22:36:52') 才会正常，我以为，会自动显示。。。

我是说图里的日期，如何显示中文？
![image](https://github.com/fi3ework/hexo-theme-archer/assets/26433019/462bbc4d-922b-4010-ba10-1e32450d6d37)
