### ISSUE TITLE
字数统计不准确

### ISSUE THREAD

**Issue by hyy34** [fi3ework/hexo-theme-archer#383]
根据教程操作，难道是我哪里操作不对了吗？

![image](https://github.com/fi3ework/hexo-theme-archer/assets/26433019/cb95eb6b-d867-47b0-9cdb-85bb688dca1a)

**Comment by Stark-X** [comment]
字数统计使用的库是 https://github.com/willin/hexo-wordcount ，可以在你本地用 nodejs 尝试一下它的实现，如果发现原因在哪，或者认为这是个bug，可以提交 issue 到它们的仓库。
