### ISSUE TITLE
可能是代码区域标记和行高不足造成的显示不全

### ISSUE THREAD

**Issue by ToonoW** [fi3ework/hexo-theme-archer#4]
![image](https://user-images.githubusercontent.com/12607586/30317499-dbfaf0a8-97dc-11e7-879f-9ba5af17ed4d.png)

这是在正文里面的H2标题，添加了代码标记就部分字母显示不全了（例如字母g）。乍一看并不是很明显。不知道算不算bug。

**Comment by fi3ework** [comment]
感谢老铁反馈，已修复😆
