### ISSUE TITLE
Windows下gulp build失败

### ISSUE THREAD

**Issue by ZhangqianStudio** [fi3ework/hexo-theme-archer#40]
![image](https://user-images.githubusercontent.com/19299425/36100403-1a2c737e-1041-11e8-8213-c53e7978bbd0.png)
RT，Nodejs为8.9.4，gulp在全局和当前项目下都有进行安装

**Comment by fi3ework** [comment]
看下这个 [issue](https://github.com/sass/node-sass/issues/468#issuecomment-229845320)，重装一下sass试一下。

**Comment by ZhangqianStudio** [comment]
成功了 蟹蟹

**Comment by fi3ework** [comment]
😆
