### ISSUE TITLE
[Bug] QR Code can't dispaly well sometimes. 二维码有时无法正常显示

### ISSUE THREAD

**Issue by acbetter** [fi3ework/hexo-theme-archer#43]
如图，高度是 `auto` 没有占满啊。。。

![image](https://user-images.githubusercontent.com/13360124/36639965-1348f0e4-1a52-11e8-8741-b37db5e8c45b.png)

**Comment by fi3ework** [comment]
不是高度的问题，是footer挡到了下半部分，你写一篇文章稍微撑开一点就不会有这样的情况了，这个bug会fix的，感谢反馈。😀

**Comment by acbetter** [comment]
感谢作者及时更新，谢谢🎉
