### ISSUE TITLE
表格和框图

### ISSUE THREAD

**Issue by MAGI003769** [fi3ework/hexo-theme-archer#47]
您好，
我平常使用typora进行markdown的编辑，在创建博客的时候遇到了下面两个问题
1. 表格的渲染有问题，没有边框
2. 用mermaid做的框图无法渲染，不知道这个是不是需要另外的插件，试了一个hexo-tag-mermaid还是不行，不知道作者有没有打算支持mermaid
希望您有空可以看一看，非常感谢您的工作，这个主题还是很nice的

**Comment by fi3ework** [comment]
你好，
1. 可以先看下这个[issue](https://github.com/fi3ework/hexo-theme-archer/issues/35)，看是不是这个问题
2. 没听说过mermaid，明天我去看下哈，如果可以就支持一下

**Comment by MAGI003769** [comment]
| Operation        | Symbol |                         Illustration      |
| ---------------- | ------ | ----------------------------------------- |
| Bit-wise AND     | &      |                                           |
| Bit-wise OR      | \|     |                                           |
| Bit-wise XOR     | ^      |                                           |
| Invert           | ~      |                                           |
| Shift left       | <<     |  Logic Shift: covering positions with 0s  |
| Shift right      | \>>    |  Logic Shift: covering positions with 0s  |
| Shift (unsigned) | \>>>   | Arithmetic Shift: original right-side bits will be shifted to the left-side |

回的这么快的吗，非常感谢
不是很清楚这个语法哪里有问题，换行具体说的是哪个地方？
我这个插件用的应该是hexo-renderer-kramed，是之前解决公式渲染时候换的，不知道是不是和这个有关系......

**Comment by fi3ework** [comment]
需要发一下你表格这块的md源码哈，这样发github已经渲染过了。
还有我看你的主题用的还是很久之前的了，可以先更新一下。
