### ISSUE TITLE
404渲染失败！！不知道是什么原因造成的

### ISSUE THREAD

**Issue by JianqingWeng** [fi3ework/hexo-theme-archer#48]
![image](https://user-images.githubusercontent.com/25848511/36945558-576d5190-1feb-11e8-9382-03d6fbb71537.png)

**Comment by fi3ework** [comment]
更新了一下[wiki](https://github.com/fi3ework/hexo-theme-archer/wiki/%E5%90%AF%E7%94%A8404%E9%A1%B5)，原来的没说清楚，是要写成meta的格式，加 ---

**Comment by JianqingWeng** [comment]
嗯嗯，好了，谢谢这么快回复

**Comment by fi3ework** [comment]
😀
