### ISSUE TITLE
更新主题的问题

### ISSUE THREAD

**Issue by a334713698** [fi3ework/hexo-theme-archer#49]
主题作者如果对主题有新代码提交，除了重新下载整个代码，有木有更新的方法呢

**Comment by fi3ework** [comment]
一般来说你在archer目录直接pull就可以到最新版。
但是如果我改了默认的_config.yml的话，git可能会出现合并冲突，到时候会提示你解决冲突，你就手动解决一下冲突，保留你的改动。

**Comment by a334713698** [comment]
感谢解答！

**Comment by fi3ework** [comment]
:smile:
