### ISSUE TITLE
该主题在Safari浏览器中无法打开

### ISSUE THREAD

**Issue by pencoa** [fi3ework/hexo-theme-archer#54]
![default](https://user-images.githubusercontent.com/7123063/37252539-7b381160-255d-11e8-906e-1eb722215357.png)

在Safari浏览器中打开效果如图

**Comment by fi3ework** [comment]
1. 在Chrome中可以打开吗
2. 可以打开这个[demo](http://firework.studio/archer-demo/)吗，我本地Safari 11.0.3可以打开
😀

**Comment by pencoa** [comment]
1. 在Chrome中可以很好打开哦，考虑到Safari是Mac主要浏览器，所以提出这个问题；
2. 我的浏览器版本信息是 _版本 11.0.3 (13604.5.6)_，这个demo也是一直没办法加载出来呢

**Comment by fi3ework** [comment]
我的Mac的Safari版本与你完全一致，刚刚清空了缓存关闭了代理试了下还是可以打开demo，能否截图控制台里的错误信息给我看下呢😀

**Comment by pencoa** [comment]
打开控制台之后显示
![1](https://user-images.githubusercontent.com/7123063/37254495-a044f20e-2579-11e8-8aba-412a6cbc178a.png)
然后发现这个错误是由于打开了Safari的Webdriver插件导致的，把这个停止掉，就可以正常打开啦。
![2](https://user-images.githubusercontent.com/7123063/37254511-dbeddc44-2579-11e8-87ad-bdedf42edb1c.png)

**Comment by pencoa** [comment]
感谢up主

**Comment by fi3ework** [comment]
😄have fun
