### ISSUE TITLE
生成右边有catalog的页面时，左边文章的锚链接位置会有一个字符，怎么去掉？

### ISSUE THREAD

**Issue by deuxer** [fi3ework/hexo-theme-archer#55]
如题

**Comment by fi3ework** [comment]
一个字符指的是什么呢..
![image](https://user-images.githubusercontent.com/12322740/37385731-4bc0ebc0-2790-11e8-9e86-888d0a580725.png)

**Comment by deuxer** [comment]
![default](https://user-images.githubusercontent.com/18586954/37389263-9889aaa6-279e-11e8-89b7-1191d837301f.png)

**Comment by deuxer** [comment]
出现在文章部分==。

**Comment by fi3ework** [comment]
改一下`hexo-theme-archer/src/js/init.js`
![image](https://user-images.githubusercontent.com/12322740/37389420-3fa2ff90-279f-11e8-912b-98040d0fcf80.png)
可以把这段代码直接删了，或者有兴趣也可以改下anchor的样式。
然后重新生成主题即可，方法见文档里的二次开发文档。

**Comment by fi3ework** [comment]
我也觉得这个anchor不好看，改成hover时才在右边显示一个anchor了，pull一下就行了。:smile:

**Comment by XShandow** [comment]
能改成和目录显示一样的数字吗
