### ISSUE TITLE
如何快速的换一套字体、代码框的css。比较喜欢markdownpad-github.css的样式

### ISSUE THREAD

**Issue by XShandow** [fi3ework/hexo-theme-archer#58]
如何快速的换一套字体、代码框的css。比较喜欢markdownpad-github.css的样式 #

**Comment by fi3ework** [comment]
@XShandow  换post页的字体在`hexo-theme-archer/src/scss/_partial/_post-p`这，代码样式在`hexo-theme-archer/src/scss/_partial/_post/_code.scss`，暂时只能自己调，也许有那种快速的修改markdown样式的npm包或css包，但是我还没发现有，如果你发现了也可以告诉我，我去看下😄
