### ISSUE TITLE
多说评论不能使用了，请问能出个配置gitment教程么？

### ISSUE THREAD

**Issue by zhihaozhang** [fi3ework/hexo-theme-archer#6]
https://www.tiexo.cn/gitment/

**Comment by fi3ework** [comment]
你好，可以参照[二次开发文档](https://github.com/fi3ework/hexo-theme-archer/blob/master/docs/develop-guide.md)，在post.ejs模板中的`</main>`标签前。按照gitment的[配置教程](https://imsun.net/posts/gitment-introduction/)加入gitment的代码。
总的来说步骤就是：

1. npm install
2. 在`</main>`前加入gitment的代码，配置按照gitment的教程填写
3. 执行gulp build

之后再重新生成就可以了，应该是没问题的，虽然我没自己试过（逃

**Comment by fi3ework** [comment]
你好，配置成功了吗，我预计会在这几天把其他评论的一键配置也加上去

**Comment by zhihaozhang** [comment]
谢谢！成功了，但我最终还是用了livere.

**Comment by fi3ework** [comment]
那就好，感谢使用😆😆😆

**Comment by zhihaozhang** [comment]
哪里，应该我谢谢你提供了这么好的模板。对了，rss订阅功能也增加以下吧。

**Comment by fi3ework** [comment]
会加的:laughing:

**Comment by zhihaozhang** [comment]
催更rss订阅功能。。。

**Comment by fi3ework** [comment]
好的，不出意外今天之内:bowtie:

**Comment by fi3ework** [comment]
已添加。

**Comment by fi3ework** [comment]
已添加。

**Comment by zhihaozhang** [comment]
我自己进行了一点开发，因此现在想自己直接弄rss功能。我npm install hexo-generator-feed --save之后，发现rss没有和其他social内容一样的logo，请问logo怎么加进去？

**Comment by fi3ework** [comment]
应该是有的吧，在social字段下加入`rss:/atom`没有吗，你可以看下我的demo，就有个rss的图标

**Comment by zhihaozhang** [comment]
pull一下是什么意思？

**Comment by fi3ework** [comment]
就是我更新代码了，push到github了，你用的还是老的，得把我的更新pull下来才行。

**Comment by zhihaozhang** [comment]
我知道，但我已经做了一点二次开发，想自己弄rss功能来着。。pull下来我做的那部分就没了，我自己试着搞rss功能，却发现rss没有其他social类似的logo，发现pull下来你的是有logo的，所以问你logo怎么加的。

**Comment by fi3ework** [comment]
就是在social字段添加`rss: /atom.xml`，rss就有图标了，链接指向的是那个xml，如果你是自定义的xml的话，就不要装那个插件用你自己的xml就好。可以发你一下你的配置文件看下吗

**Comment by zhihaozhang** [comment]
# ========== Profile ========== #
# avatar
avatar: /avatar/kumamon.jpg
# author name
author: Zhihao Zhang
# signature
signature: Happy Hacking
# SNS
social:
  email:  zhihaozhang@me.com
  github: https://github.com/zhihaozhang
  weibo: http://weibo.com/2854428840/profile?rightmod=1&wvr=6&mod=personinfo
  zhihu: https://www.zhihu.com/people/zhihao-zhang-95/activities
  # facebook:
  twitter: https://twitter.com/Chih_hao_
  instagram: https://www.instagram.com/izhihao_zhang/
  rss: /atom.xml

  # rss: "/atom.xml"
  # stack-overflow:
  # linkedin:
# friends
friends:
  Chase.Zhang: https://io-meter.com
#   friendB: //www.google.com
  # friendC :
about:
  enable: true
  image: '/intro/about-page.jpg'

# ========== Site ========== #
# title of the site
SEO_title: Zhihao's Studio
# main title
main_title: Zhihao's Studio.
# subtitle
subtitle: 每天进步一点点
# site haeder image
site_header_image: '/intro/about-page1.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Com∂t ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加
comment:
  # change the value of livere to your livere data-uid
  livere: MTAyMC8zMTAyMC83NTY5

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: false
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assests/favicon.ico
# truncate length (the default is 300)
truncate_length:
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/

**Comment by fi3ework** [comment]
我看你已经push了你的blog，但你是主题的版本还是v20170912啊，得更新

**Comment by fi3ework** [comment]
是哪部分冲突了呢，你先备份你的修改，然后pull之后再覆盖呢
