### ISSUE TITLE
右边catalog高亮章节问题

### ISSUE THREAD

**Issue by kurobanekid** [fi3ework/hexo-theme-archer#62]
点击右边catalog章节列表，确实会实现跳转，但是列表仍高亮跳转前的章节，需要滚动一下才能正确高亮当前（跳转后）的章节

**Comment by fi3ework** [comment]
因为往下滚1px才进入了你点的那个标题的boudingRect，确实是个bug，过几天fix😂

**Comment by fi3ework** [comment]
顺便看了下你blog，感觉还得再加个`版权声明`，每次要写太麻烦了😂

**Comment by kurobanekid** [comment]
哈哈，对

**Comment by XShandow** [comment]
![image](https://user-images.githubusercontent.com/15667872/37573975-33e573b0-2b58-11e8-94c7-520b584a0dc3.png)

显示的不对应啊

**Comment by fi3ework** [comment]
@XShadow pull一下，最近改了这个bug

**Comment by XShandow** [comment]
从没见过这么勤劳的作者了 66666
