### ISSUE TITLE
为啥我的toc不能自动伸缩呀 而且排版也不正常

### ISSUE THREAD

**Issue by tabris233** [fi3ework/hexo-theme-archer#63]
!!! md 最新版本还上传不上去．．．．．　，，，，　以下问题是放屁，，，

还有个问题就是有一篇文章莫名出现一大堆`<br>` ... 

[戳这里](http://tabris.top/2018/03/17/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%89%8B%E5%86%8C/)

排版不正常的比如说这个 
[戳这里](http://tabris.top/2018/01/29/2018-1-29/)

不能是我Markdown的姿势有问题吧,,,,

而且我的Markdown导不进去图片,,  这个应该是姿势问题,, 但是vscode预览有图片 `hexo g`后就没有.....

**Comment by fi3ework** [comment]
@tabris233 
1 这两个md文件可以发我邮箱一下嘛，我看下是写作姿势的问题还是我css的问题还是hexo的md解释器的问题
2 如果用本地图片，要用相对路径的😀

**Comment by tabris233** [comment]
toc的问题找到了  
我使用 ## (二级标题) 之后习惯直接用 #### (四级标题)  对其的时候是按照四级标题对其的,然后就出问题啦,  我只要吧缺少的 ### 补上就可以了,

一大堆空格的那个 [戳这里](https://github.com/tabris233/Other/blob/master/fuck/page3.md)

**Comment by fi3ework** [comment]
@tabris233 
1. toc那个确实要严格按照层级来些，ps：可以pull一下，昨天更新fix了toc相关的bug
2. md爆br的问题，不是主题的锅，也不是姿势的锅，你发的那个md，应该是从csdn直接拷贝的吧，这个准确来说就是html了，md解释器理论上可以支持html的渲染，但是支持到什么程度要看md解释器，github的解释器很好，所以你放在github上没问题。但是hexo的解释器很挫，所以解释出了一堆`<br />`。
