### ISSUE TITLE
请问一下首页的每个文章的标题的样式是在哪个地方修改

### ISSUE THREAD

**Issue by FortuneC00kie** [fi3ework/hexo-theme-archer#66]
![image](https://user-images.githubusercontent.com/26539482/37746534-ac94856c-2db5-11e8-8dea-08821b44c39c.png)

**Comment by fi3ework** [comment]
[这里哦](https://github.com/fi3ework/hexo-theme-archer/blob/master/src/scss/_partial/_index-page.scss#L21-L33)

**Comment by FortuneC00kie** [comment]
thankyou! 还有就是我想把首页的那个标题与文章内容的之前的间距增大一下，是哪个属性
