### ISSUE TITLE
安装sitemap插件出错?

### ISSUE THREAD

**Issue by lishuqiang** [fi3ework/hexo-theme-archer#67]
代码如下：
npm WARN checkPermissions Missing write access to D:\blog\node_modules\nan
npm ERR! path D:\blog\node_modules\nan
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'D:\blog\node_modules\nan'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2018-03-22T13_56_54_701Z-debug.log

**Comment by fi3ework** [comment]
这个没遇到过额，可以尝试删除 `node_modules`  再重新执行 `npm i`

**Comment by lishuqiang** [comment]
我刚试了，已解决。谢谢！
