### ISSUE TITLE
公式支持问题

### ISSUE THREAD

**Issue by pzs741** [fi3ework/hexo-theme-archer#68]
这个主题支持'katex'公式吗？如果不支持，要怎样去加载插件并显示呢？

**Comment by fi3ework** [comment]
可以看下[这个插件](https://github.com/hexojs/hexo-math) 和 [这个教程](http://lowrank.science/Hexo-KaTeX/) 介绍了两种支持 katex 的方法，搜一下`hexo katex`也有一些对应的教程，我本身没用过katex，如果还有什么问题可以继续留言。
