### ISSUE TITLE
关于hexo-generator-json-content...

### ISSUE THREAD

**Issue by jxai** [fi3ework/hexo-theme-archer#7]
不好意思,刚开始接触hexo。。
按照文档安装了hexo-generator-json-content，在根目录_config.yml里添加配置：
jsonContent:
meta: false
pages: false
  posts:
title: true
date: true
path: true
text: false
raw: false
content: false
slug: false
updated: false
comments: false
link: false
permalink: false
excerpt: false
categories: false
tags: true

然后查看网页源码的时候，在底部发现这一段：

‘’‘

<div class="tag-load-fail" style="display: none; color: #ccc; font-size: 0.6rem;">
--
  | 缺失模块。<br/>
  | 1、请确保node版本大于6.2<br/>
  | 2、在博客根目录（注意不是archer根目录）执行以下命令：<br/>
  | <span style="color: #f75357; font-size: 1rem; line-height: 2rem;">npm i hexo-generator-json-content --save</span><br/>
  | 3、在根目录_config.yml里添加配置：
  | <pre style="color: #888; font-size: 0.6rem;">
  | jsonContent:
  | meta: false
  | pages: false
  | posts:
  | title: true
  | date: true
  | path: true
  | text: false
  | raw: false
  | content: false
  | slug: false
  | updated: false
  | comments: false
  | link: false
  | permalink: false
  | excerpt: false
  | categories: false
  | tags: true</pre>
  | </div>

’‘’

<div class="tag-load-fail" style="display: none; color: #ccc; font-size: 0.6rem;">
--
  | 缺失模块。<br/>
  | 1、请确保node版本大于6.2<br/>
  | 2、在博客根目录（注意不是archer根目录）执行以下命令：<br/>
  | <span style="color: #f75357; font-size: 1rem; line-height: 2rem;">npm i hexo-generator-json-content --save</span><br/>
  | 3、在根目录_config.yml里添加配置：
  | <pre style="color: #888; font-size: 0.6rem;">
  | jsonContent:
  | meta: false
  | pages: false
  | posts:
  | title: true
  | date: true
  | path: true
  | text: false
  | raw: false
  | content: false
  | slug: false
  | updated: false
  | comments: false
  | link: false
  | permalink: false
  | excerpt: false
  | categories: false
  | tags: true</pre>
  | </div>

嗯。。。虽然此主题在使用上暂时没遇上什么问题。。

但是。。看着糟心啊。。

并且。。。。作者你的演示博客也是一样有这个问题。。请问怎么解决呢？还是说没影响呢。

**Comment by fi3ework** [comment]
你好，感谢使用，我看了下我的主页和你的主页的元素好像并没有你所说的这个失败提示，你指的源码是工程项目里的源码吗？如果成功加载了json的话会删除掉这个失败的提示的元素的😀
