### ISSUE TITLE
请问可以增加一个暗色背景的代码高亮嘛，谢谢

### ISSUE THREAD

**Issue by FortuneC00kie** [fi3ework/hexo-theme-archer#71]

**Comment by kurobanekid** [comment]
![snipaste20180324_194846](https://user-images.githubusercontent.com/15232298/37863650-66d016f2-2f9c-11e8-8283-78fb203d54b2.png)
我觉得这种不错

**Comment by fi3ework** [comment]
会增加的，不过最近事比较多，要晚一点

**Comment by FortuneC00kie** [comment]
好的👌，谢谢大佬
