### ISSUE TITLE
关于md语法不支持问题 

### ISSUE THREAD

**Issue by DomBro96** [fi3ework/hexo-theme-archer#75]
你好，首先很喜欢你的主题。在最近一次更博时，发现md语法的注脚和时序图在主体中不能渲染(我确定语法是正确的)。前端白痴一枚，求赐教。

**Comment by fi3ework** [comment]
你好，这是hexo的md解释器的问题，可能对注脚和时序图的支持不好，可以参见![这里](https://github.com/bubkoo/hexo-filter-flowchart)获得一些帮助或直接搜索`hexo 时序图`
