### ISSUE TITLE
使用畅言评论插件 登录框在最上面。。

### ISSUE THREAD

**Issue by kosmosr** [fi3ework/hexo-theme-archer#76]
如图 是什么情况呢 [我的博客](http://mollysu.top) 使用别的不会这样：
![QQ20180411103535.jpg](http://www.wailian.work/images/2018/04/11/QQ20180411103535.jpg)

**Comment by fi3ework** [comment]
这个好像是fixed布局与flex布局的冲突，只能说畅言布局的兼容性不太好了，影响不大。
