### ISSUE TITLE
如何修改chrome上显示的网站logo

### ISSUE THREAD

**Issue by jiaruixu** [fi3ework/hexo-theme-archer#77]
Hello, 想问一下怎么把网站的logo改成自己头像呢？我这一直显示的是你的头像，很奇怪。
￼
![1](https://user-images.githubusercontent.com/34403859/38600380-edc14206-3d31-11e8-8478-26d6256cd693.jpg)

**Comment by fi3ework** [comment]
找到favicon.ico这个文件，然后替换成你的就好了。

**Comment by jiaruixu** [comment]
解决啦～～谢谢！
