### ISSUE TITLE
README 中置顶文章的链接失效了

### ISSUE THREAD

**Issue by secsilm** [fi3ework/hexo-theme-archer#78]
`README.md`  中可选配置部分最后一条：[置顶文章](http://xxxsss.me/2017/04/22/hexo-pagination/) 链接失效了。

![](https://i.imgur.com/7NWcEcD.png)

**Comment by fi3ework** [comment]
@secsilm

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： https://github.com/hexojs/hexo-generator-index/pull/51
