### ISSUE TITLE
浏览界面比例放大时，CATALOG与博文内容重叠问题

### ISSUE THREAD

**Issue by kurobanekid** [fi3ework/hexo-theme-archer#8]
PC网页端阅读博文，放大浏览界面时，右边的CATALOG会和博文内容相交（交叠）在一起。当放大到一定比例时，右边的CATALOG才会消失。另外移动端sidebar用移动端chrome浏览器和小米浏览器会显示，但是UC和夸克浏览器并不能显示（注：UC和夸克的内核是一样的）

**Comment by fi3ework** [comment]
1. toc那个放大时确实有问题，会尽快修复。放大到一定比例时就进入了移动端模式，移动端不显示toc所以就消失了。
2. 移动端sidebar的bug在刚刚提交的那个版本已经修复了，pull一下就好。
感谢使用😀

**Comment by kurobanekid** [comment]
嗯嗯
