### ISSUE TITLE
文章的 Catalog 在低分屏上显示不全 

### ISSUE THREAD

**Issue by thegreatestkingofbunny** [fi3ework/hexo-theme-archer#83]
## 分辨率信息
系统: Windows 10
文本缩放: 150%
系统分辨率: 1920x1080
<img width="960" alt="default" src="https://user-images.githubusercontent.com/38251422/39041036-bc802848-44ba-11e8-9fcb-7ffe84d59a4e.PNG">

希望支持低分屏

**Comment by fi3ework** [comment]
具体的问题是？我好像没从你的截图上看出什么问题...

**Comment by thegreatestkingofbunny** [comment]
在某些时候 catalog 不会自动折叠，导致所有的标题都展开了，最下面的标题显示不全。后来就没有复现过同样的 Bug 了。可能是浏览器的问题，我先关闭issue。

**Comment by fi3ework** [comment]
我猜是第一次的时候发生的这个问题吧，以100%进入之后各个标题的位置就是按100%确定的，之后切换到150%就会导致错位，除第一次之外应该就都是按150%初始化位置了。
