### ISSUE TITLE
关于阅读全文

### ISSUE THREAD

**Issue by slow-sky** [fi3ework/hexo-theme-archer#86]
希望能增加阅读全文的选项，我用<不知道为什么也不能显示摘要，直接默认显示显得很乱。

**Comment by fi3ework** [comment]
什么意思。。。点进去不就是阅读全文吗。。

**Comment by fi3ework** [comment]
[自定义文章在首页的摘要](https://github.com/fi3ework/hexo-theme-archer/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E7%AB%A0%E5%9C%A8%E9%A6%96%E9%A1%B5%E6%91%98%E8%A6%81)
