### ISSUE TITLE
文字、图标偏移

### ISSUE THREAD

**Issue by kurobanekid** [fi3ework/hexo-theme-archer#87]
更新5.1号版本后，左上角的箭头发生偏移，文章标题下的日期、浏览人数、分享有偏移

**Comment by fi3ework** [comment]
能截下图和说下浏览器吗，我这是好的。。

**Comment by kurobanekid** [comment]
![xx.png](https://kurobaneblog.oss-cn-shenzhen.aliyuncs.com/issue.png)
![xx.png](https://kurobaneblog.oss-cn-shenzhen.aliyuncs.com/issue2.png)

**Comment by fi3ework** [comment]
windows吗

**Comment by fi3ework** [comment]
:joy: 我也发现了，确实在windows下会这样，我看下

**Comment by kurobanekid** [comment]
嗯嗯👍

**Comment by fi3ework** [comment]
@kurobanekid 已经 fix 了，是 iconfont 的问题，不知道为什么就有个偏移，重新生成了一次就好了，感谢反馈

**Comment by kurobanekid** [comment]
现在图标都显示不出来了，显示的就是一个小方框😂

**Comment by fi3ework** [comment]
可是我看你的主页已经OK了啊。。清缓存了吧
![image](https://user-images.githubusercontent.com/12322740/39569605-4af04b7a-4ef8-11e8-9ffd-58c1a22d4b73.png)

**Comment by kurobanekid** [comment]
可以了😀

**Comment by fi3ework** [comment]
好的，刚才发现好像之前loading的问题还是存在，如果又发现麻烦在控制台截个图开个issue再反馈下，多谢 @kurobanekid :joy:

**Comment by kurobanekid** [comment]
嗯嗯😁
