### ISSUE TITLE
hexo-neat插件 压缩会报错

### ISSUE THREAD

**Issue by lemonL** [fi3ework/hexo-theme-archer#89]
![00](https://user-images.githubusercontent.com/5005866/39661159-bc3e0c26-507f-11e8-8b5a-ffa0c3c3ba8a.png)

**Comment by fi3ework** [comment]
我没用过 hexo-neat，看报错似乎是 preload 这句它没认出来，那是不是 hexo-neat 的问题。。
而且 js 和 css 主题里已经压缩过了（html 忘了压缩了，下个版本压缩掉，逃），应该就不用 hexo-neat 了

**Comment by fi3ework** [comment]
我试了下 hexo-neat 及其他的压缩 html 的插件，确实是不行。似乎是带 preload 的 link 标签的 onload 回调无法正确解析。
有两种解决方法吧：
1. 等有时间我研究下 html压缩的插件的代码，看能不能提个pr修复一下，不过不能保证时效性。
2. 用 gulp 做，不使用压缩插件（或使用插件，但不开启对html压缩的选项。再或者用也行，因为报错了就不压缩了，相当于什么都没做）进行 hexo g，然后 gulp 压缩一下 html，再 hexo d，这种修改的工作量较低，但是缺点是即使不开发也要装一个 gulp 全家桶，每次 d 还得多敲一个命令行，写在 npm script
 里可以但是这样就不够无脑了

**Comment by lemonL** [comment]
@fi3ework   大神。我刚对前端还没有你了解深。:sweat:  ,想提pr ，有心无力:joy:
