### ISSUE TITLE
关于分类和标签的问题

### ISSUE THREAD

**Issue by czk-kong2018** [fi3ework/hexo-theme-archer#94]
请问哪个分类和标签只能显示吗，修改哪里能自定义到指定文章下，就是 点击分类标签会显示出分类下的所有文章 点击文章进入到文章里

**Comment by fi3ework** [comment]
我没太明白你的意思。。
你可以看下 [demo](http://firework.studio/archer-demo/)，点击分类/标签，会显示对应的文章链接，点进去就是文章。
分类和标签在每个文章的 meta 里写，具体的可以去看下 hexo 的文档
