### ISSUE TITLE
文章的浏览人数计数方式怎么改成uv模式?

### ISSUE THREAD

**Issue by kuraraneko** [fi3ework/hexo-theme-archer#96]
博客的浏览量把\archer\layout\_partial\base-footer.ejs里的busuanzi_container_site_pv和busuanzi_value_site_pv改成busuanzi_container_site_uv和busuanzi_value_site_uv.
但文章的浏览量一直没成功改为uv模式

**Comment by fi3ework** [comment]
按理说你的操作是对的，也许是busuanzi的问题，比如你的pv已经是1000了，你再改为uv，之后的计算会在1000上加，而不是重新置零统计uv。
我会在config中添加一个uv和pv的可选参数。
